// provided.js - generated by ephemient/aoc2022/Kotlin benchmarks, 2022-12-07 08:54:48.565833328

var providedBenchmarks = ["graalBench","jvmBench","linuxX64Bench"];

var providedBenchmarkStore = {
  "graalBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4864.103461469613,
        "scoreError": 513.907510693154,
        "scoreConfidence": [
          4350.195950776459,
          5378.010972162767
        ],
        "scorePercentiles": {
          "0.0": 4695.249985462572,
          "50.0": 4936.870251548506,
          "90.0": 4971.868203922059,
          "95.0": 4971.868203922059,
          "99.0": 4971.868203922059,
          "99.9": 4971.868203922059,
          "99.99": 4971.868203922059,
          "99.999": 4971.868203922059,
          "99.9999": 4971.868203922059,
          "100.0": 4971.868203922059
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4695.249985462572,
            4971.751248920403,
            4936.870251548506,
            4971.868203922059,
            4744.777617494522
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4940.386340903618,
        "scoreError": 270.49555756829903,
        "scoreConfidence": [
          4669.890783335319,
          5210.881898471916
        ],
        "scorePercentiles": {
          "0.0": 4832.749140734606,
          "50.0": 4935.705411701983,
          "90.0": 5013.391680066932,
          "95.0": 5013.391680066932,
          "99.0": 5013.391680066932,
          "99.9": 5013.391680066932,
          "99.99": 5013.391680066932,
          "99.999": 5013.391680066932,
          "99.9999": 5013.391680066932,
          "100.0": 5013.391680066932
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4991.888201647866,
            5013.391680066932,
            4832.749140734606,
            4935.705411701983,
            4928.197270366697
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10255.04360675853,
        "scoreError": 773.3011754283601,
        "scoreConfidence": [
          9481.74243133017,
          11028.34478218689
        ],
        "scorePercentiles": {
          "0.0": 9901.259175773861,
          "50.0": 10340.130634429208,
          "90.0": 10374.453092514694,
          "95.0": 10374.453092514694,
          "99.0": 10374.453092514694,
          "99.9": 10374.453092514694,
          "99.99": 10374.453092514694,
          "99.999": 10374.453092514694,
          "99.9999": 10374.453092514694,
          "100.0": 10374.453092514694
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9901.259175773861,
            10374.453092514694,
            10340.130634429208,
            10287.761452569302,
            10371.613678505582
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 8815.12313733601,
        "scoreError": 794.8499443294228,
        "scoreConfidence": [
          8020.273193006587,
          9609.973081665432
        ],
        "scorePercentiles": {
          "0.0": 8585.22296186957,
          "50.0": 8860.753105962176,
          "90.0": 9104.178527002103,
          "95.0": 9104.178527002103,
          "99.0": 9104.178527002103,
          "99.9": 9104.178527002103,
          "99.99": 9104.178527002103,
          "99.999": 9104.178527002103,
          "99.9999": 9104.178527002103,
          "100.0": 9104.178527002103
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            8860.753105962176,
            8877.747296589967,
            8585.22296186957,
            9104.178527002103,
            8647.713795256233
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 8245.676725423895,
        "scoreError": 462.0558538024206,
        "scoreConfidence": [
          7783.620871621474,
          8707.732579226315
        ],
        "scorePercentiles": {
          "0.0": 8111.658232046486,
          "50.0": 8223.08021446209,
          "90.0": 8424.061160203673,
          "95.0": 8424.061160203673,
          "99.0": 8424.061160203673,
          "99.9": 8424.061160203673,
          "99.99": 8424.061160203673,
          "99.999": 8424.061160203673,
          "99.9999": 8424.061160203673,
          "100.0": 8424.061160203673
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            8294.227441644756,
            8223.08021446209,
            8111.658232046486,
            8175.356578762466,
            8424.061160203673
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 9206.650981560564,
        "scoreError": 588.5523172896626,
        "scoreConfidence": [
          8618.098664270901,
          9795.203298850227
        ],
        "scorePercentiles": {
          "0.0": 9033.730173718131,
          "50.0": 9299.915377468564,
          "90.0": 9341.43570981487,
          "95.0": 9341.43570981487,
          "99.0": 9341.43570981487,
          "99.9": 9341.43570981487,
          "99.99": 9341.43570981487,
          "99.999": 9341.43570981487,
          "99.9999": 9341.43570981487,
          "100.0": 9341.43570981487
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9299.915377468564,
            9341.43570981487,
            9311.676866985163,
            9046.496779816085,
            9033.730173718131
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1024.1007394044348,
        "scoreError": 68.30017149503455,
        "scoreConfidence": [
          955.8005679094002,
          1092.4009108994694
        ],
        "scorePercentiles": {
          "0.0": 993.1445350918079,
          "50.0": 1031.287209344666,
          "90.0": 1036.2536207133696,
          "95.0": 1036.2536207133696,
          "99.0": 1036.2536207133696,
          "99.9": 1036.2536207133696,
          "99.99": 1036.2536207133696,
          "99.999": 1036.2536207133696,
          "99.9999": 1036.2536207133696,
          "100.0": 1036.2536207133696
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            993.1445350918079,
            1025.8255101581985,
            1033.9928217141314,
            1036.2536207133696,
            1031.287209344666
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1034.771425947874,
        "scoreError": 46.015225899756636,
        "scoreConfidence": [
          988.7562000481173,
          1080.7866518476305
        ],
        "scorePercentiles": {
          "0.0": 1018.2796007856709,
          "50.0": 1036.0782065088583,
          "90.0": 1048.03887813015,
          "95.0": 1048.03887813015,
          "99.0": 1048.03887813015,
          "99.9": 1048.03887813015,
          "99.99": 1048.03887813015,
          "99.999": 1048.03887813015,
          "99.9999": 1048.03887813015,
          "100.0": 1048.03887813015
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1036.0782065088583,
            1027.9952713456307,
            1018.2796007856709,
            1048.03887813015,
            1043.46517296906
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1772.5492918985328,
        "scoreError": 139.24266521787092,
        "scoreConfidence": [
          1633.3066266806618,
          1911.7919571164039
        ],
        "scorePercentiles": {
          "0.0": 1719.3532877830312,
          "50.0": 1788.5860103048828,
          "90.0": 1804.6386419662144,
          "95.0": 1804.6386419662144,
          "99.0": 1804.6386419662144,
          "99.9": 1804.6386419662144,
          "99.99": 1804.6386419662144,
          "99.999": 1804.6386419662144,
          "99.9999": 1804.6386419662144,
          "100.0": 1804.6386419662144
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1751.6229438934745,
            1719.3532877830312,
            1798.5455755450607,
            1804.6386419662144,
            1788.5860103048828
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1966.2368328641903,
        "scoreError": 43.04823900143752,
        "scoreConfidence": [
          1923.188593862753,
          2009.2850718656277
        ],
        "scorePercentiles": {
          "0.0": 1951.8366486692244,
          "50.0": 1971.3285418427058,
          "90.0": 1976.4310665086955,
          "95.0": 1976.4310665086955,
          "99.0": 1976.4310665086955,
          "99.9": 1976.4310665086955,
          "99.99": 1976.4310665086955,
          "99.999": 1976.4310665086955,
          "99.9999": 1976.4310665086955,
          "100.0": 1976.4310665086955
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1951.8366486692244,
            1956.7851084407882,
            1971.3285418427058,
            1974.8027988595386,
            1976.4310665086955
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2248.989850896703,
        "scoreError": 220.7552136978616,
        "scoreConfidence": [
          2028.2346371988415,
          2469.7450645945646
        ],
        "scorePercentiles": {
          "0.0": 2162.9621804643425,
          "50.0": 2248.145900146638,
          "90.0": 2304.466138012886,
          "95.0": 2304.466138012886,
          "99.0": 2304.466138012886,
          "99.9": 2304.466138012886,
          "99.99": 2304.466138012886,
          "99.999": 2304.466138012886,
          "99.9999": 2304.466138012886,
          "100.0": 2304.466138012886
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2162.9621804643425,
            2231.712307734698,
            2297.662728124953,
            2304.466138012886,
            2248.145900146638
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 550.0812367423258,
        "scoreError": 38.573701753069365,
        "scoreConfidence": [
          511.50753498925644,
          588.6549384953952
        ],
        "scorePercentiles": {
          "0.0": 539.7694164427593,
          "50.0": 547.259472561147,
          "90.0": 566.7587936917515,
          "95.0": 566.7587936917515,
          "99.0": 566.7587936917515,
          "99.9": 566.7587936917515,
          "99.99": 566.7587936917515,
          "99.999": 566.7587936917515,
          "99.9999": 566.7587936917515,
          "100.0": 566.7587936917515
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            547.259472561147,
            549.4672404099691,
            566.7587936917515,
            539.7694164427593,
            547.1512606060018
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1331.3665261552926,
        "scoreError": 78.6455626873014,
        "scoreConfidence": [
          1252.7209634679912,
          1410.012088842594
        ],
        "scorePercentiles": {
          "0.0": 1311.8606595120991,
          "50.0": 1319.6012890685145,
          "90.0": 1358.6074368874424,
          "95.0": 1358.6074368874424,
          "99.0": 1358.6074368874424,
          "99.9": 1358.6074368874424,
          "99.99": 1358.6074368874424,
          "99.999": 1358.6074368874424,
          "99.9999": 1358.6074368874424,
          "100.0": 1358.6074368874424
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1319.248832907031,
            1311.8606595120991,
            1358.6074368874424,
            1347.514412401376,
            1319.6012890685145
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1255.693843505591,
        "scoreError": 169.01580703913703,
        "scoreConfidence": [
          1086.6780364664542,
          1424.709650544728
        ],
        "scorePercentiles": {
          "0.0": 1187.256366723728,
          "50.0": 1267.4038829206877,
          "90.0": 1296.8392666081008,
          "95.0": 1296.8392666081008,
          "99.0": 1296.8392666081008,
          "99.9": 1296.8392666081008,
          "99.99": 1296.8392666081008,
          "99.999": 1296.8392666081008,
          "99.9999": 1296.8392666081008,
          "100.0": 1296.8392666081008
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1240.3420667524015,
            1267.4038829206877,
            1187.256366723728,
            1296.8392666081008,
            1286.6276345230374
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvmBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 22752.484848987653,
        "scoreError": 1936.0676673723583,
        "scoreConfidence": [
          20816.417181615296,
          24688.55251636001
        ],
        "scorePercentiles": {
          "0.0": 22242.99248859725,
          "50.0": 22544.548450873845,
          "90.0": 23351.854309229522,
          "95.0": 23351.854309229522,
          "99.0": 23351.854309229522,
          "99.9": 23351.854309229522,
          "99.99": 23351.854309229522,
          "99.999": 23351.854309229522,
          "99.9999": 23351.854309229522,
          "100.0": 23351.854309229522
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            22397.895778492028,
            22242.99248859725,
            22544.548450873845,
            23351.854309229522,
            23225.133217745635
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 22689.988219170074,
        "scoreError": 1210.4324171441576,
        "scoreConfidence": [
          21479.555802025916,
          23900.420636314233
        ],
        "scorePercentiles": {
          "0.0": 22266.09191665764,
          "50.0": 22818.10604107063,
          "90.0": 22999.34221881254,
          "95.0": 22999.34221881254,
          "99.0": 22999.34221881254,
          "99.9": 22999.34221881254,
          "99.99": 22999.34221881254,
          "99.999": 22999.34221881254,
          "99.9999": 22999.34221881254,
          "100.0": 22999.34221881254
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            22455.870342988055,
            22999.34221881254,
            22818.10604107063,
            22266.09191665764,
            22910.530576321507
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 26060.044053899517,
        "scoreError": 1060.4069710072658,
        "scoreConfidence": [
          24999.63708289225,
          27120.451024906783
        ],
        "scorePercentiles": {
          "0.0": 25849.18390471518,
          "50.0": 25921.619397618397,
          "90.0": 26507.314116180758,
          "95.0": 26507.314116180758,
          "99.0": 26507.314116180758,
          "99.9": 26507.314116180758,
          "99.99": 26507.314116180758,
          "99.999": 26507.314116180758,
          "99.9999": 26507.314116180758,
          "100.0": 26507.314116180758
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            25879.006642681452,
            25849.18390471518,
            25921.619397618397,
            26507.314116180758,
            26143.09620830179
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 20239.874359381087,
        "scoreError": 2614.8055883308143,
        "scoreConfidence": [
          17625.06877105027,
          22854.679947711902
        ],
        "scorePercentiles": {
          "0.0": 19067.944866441692,
          "50.0": 20564.23141645303,
          "90.0": 20688.046768169264,
          "95.0": 20688.046768169264,
          "99.0": 20688.046768169264,
          "99.9": 20688.046768169264,
          "99.99": 20688.046768169264,
          "99.999": 20688.046768169264,
          "99.9999": 20688.046768169264,
          "100.0": 20688.046768169264
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            19067.944866441692,
            20564.23141645303,
            20646.004885368395,
            20233.143860473032,
            20688.046768169264
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 16073.327176579396,
        "scoreError": 784.9517868585378,
        "scoreConfidence": [
          15288.375389720859,
          16858.278963437933
        ],
        "scorePercentiles": {
          "0.0": 15832.292104003685,
          "50.0": 16089.28442665189,
          "90.0": 16333.053003410354,
          "95.0": 16333.053003410354,
          "99.0": 16333.053003410354,
          "99.9": 16333.053003410354,
          "99.99": 16333.053003410354,
          "99.999": 16333.053003410354,
          "99.9999": 16333.053003410354,
          "100.0": 16333.053003410354
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            15914.921345261357,
            16089.28442665189,
            15832.292104003685,
            16333.053003410354,
            16197.085003569697
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 29411.892154091947,
        "scoreError": 2713.2149204268417,
        "scoreConfidence": [
          26698.677233665105,
          32125.10707451879
        ],
        "scorePercentiles": {
          "0.0": 28225.15852134411,
          "50.0": 29663.595621097844,
          "90.0": 30062.170505521088,
          "95.0": 30062.170505521088,
          "99.0": 30062.170505521088,
          "99.9": 30062.170505521088,
          "99.99": 30062.170505521088,
          "99.999": 30062.170505521088,
          "99.9999": 30062.170505521088,
          "100.0": 30062.170505521088
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            28225.15852134411,
            29663.595621097844,
            29394.855828445026,
            29713.68029405165,
            30062.170505521088
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3677.2995718151324,
        "scoreError": 340.7617442463505,
        "scoreConfidence": [
          3336.5378275687817,
          4018.061316061483
        ],
        "scorePercentiles": {
          "0.0": 3530.0129706457074,
          "50.0": 3687.8946337785605,
          "90.0": 3765.4590014434266,
          "95.0": 3765.4590014434266,
          "99.0": 3765.4590014434266,
          "99.9": 3765.4590014434266,
          "99.99": 3765.4590014434266,
          "99.999": 3765.4590014434266,
          "99.9999": 3765.4590014434266,
          "100.0": 3765.4590014434266
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3684.6849873879087,
            3687.8946337785605,
            3765.4590014434266,
            3718.446265820058,
            3530.0129706457074
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3648.806687426747,
        "scoreError": 422.40239540780414,
        "scoreConfidence": [
          3226.4042920189427,
          4071.2090828345513
        ],
        "scorePercentiles": {
          "0.0": 3465.818979037289,
          "50.0": 3679.2076886912846,
          "90.0": 3759.015109711869,
          "95.0": 3759.015109711869,
          "99.0": 3759.015109711869,
          "99.9": 3759.015109711869,
          "99.99": 3759.015109711869,
          "99.999": 3759.015109711869,
          "99.9999": 3759.015109711869,
          "100.0": 3759.015109711869
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3465.818979037289,
            3679.2076886912846,
            3688.445268249615,
            3651.546391443676,
            3759.015109711869
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4358.67873542433,
        "scoreError": 640.7575088289285,
        "scoreConfidence": [
          3717.921226595401,
          4999.436244253258
        ],
        "scorePercentiles": {
          "0.0": 4148.1025082451115,
          "50.0": 4446.140344001297,
          "90.0": 4502.856891241019,
          "95.0": 4502.856891241019,
          "99.0": 4502.856891241019,
          "99.9": 4502.856891241019,
          "99.99": 4502.856891241019,
          "99.999": 4502.856891241019,
          "99.9999": 4502.856891241019,
          "100.0": 4502.856891241019
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4210.745431307498,
            4148.1025082451115,
            4485.548502326724,
            4502.856891241019,
            4446.140344001297
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4753.712949416108,
        "scoreError": 616.3632091260828,
        "scoreConfidence": [
          4137.349740290026,
          5370.076158542191
        ],
        "scorePercentiles": {
          "0.0": 4568.270995121587,
          "50.0": 4863.400588038813,
          "90.0": 4882.709177705527,
          "95.0": 4882.709177705527,
          "99.0": 4882.709177705527,
          "99.9": 4882.709177705527,
          "99.99": 4882.709177705527,
          "99.999": 4882.709177705527,
          "99.9999": 4882.709177705527,
          "100.0": 4882.709177705527
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4568.270995121587,
            4589.235126461089,
            4863.400588038813,
            4864.948859753526,
            4882.709177705527
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4194.324117269863,
        "scoreError": 330.4650244310492,
        "scoreConfidence": [
          3863.8590928388135,
          4524.789141700912
        ],
        "scorePercentiles": {
          "0.0": 4095.568912570081,
          "50.0": 4204.360472671261,
          "90.0": 4293.901577696473,
          "95.0": 4293.901577696473,
          "99.0": 4293.901577696473,
          "99.9": 4293.901577696473,
          "99.99": 4293.901577696473,
          "99.999": 4293.901577696473,
          "99.9999": 4293.901577696473,
          "100.0": 4293.901577696473
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4095.568912570081,
            4119.494386930806,
            4204.360472671261,
            4293.901577696473,
            4258.295236480692
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 848.7362674667442,
        "scoreError": 73.9365673521319,
        "scoreConfidence": [
          774.7997001146123,
          922.672834818876
        ],
        "scorePercentiles": {
          "0.0": 816.6850121775872,
          "50.0": 853.2840537212933,
          "90.0": 867.9087826271468,
          "95.0": 867.9087826271468,
          "99.0": 867.9087826271468,
          "99.9": 867.9087826271468,
          "99.99": 867.9087826271468,
          "99.999": 867.9087826271468,
          "99.9999": 867.9087826271468,
          "100.0": 867.9087826271468
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            816.6850121775872,
            853.2840537212933,
            856.3999323404128,
            867.9087826271468,
            849.4035564672807
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2914.5848024253423,
        "scoreError": 143.64799542125732,
        "scoreConfidence": [
          2770.936807004085,
          3058.2327978465996
        ],
        "scorePercentiles": {
          "0.0": 2853.199243949572,
          "50.0": 2924.9458816786478,
          "90.0": 2945.9162741343957,
          "95.0": 2945.9162741343957,
          "99.0": 2945.9162741343957,
          "99.9": 2945.9162741343957,
          "99.99": 2945.9162741343957,
          "99.999": 2945.9162741343957,
          "99.9999": 2945.9162741343957,
          "100.0": 2945.9162741343957
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2853.199243949572,
            2908.376345289523,
            2924.9458816786478,
            2940.486267074573,
            2945.9162741343957
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2686.9492315739108,
        "scoreError": 217.9453505955355,
        "scoreConfidence": [
          2469.0038809783755,
          2904.894582169446
        ],
        "scorePercentiles": {
          "0.0": 2588.295098114157,
          "50.0": 2713.0329339846153,
          "90.0": 2725.9002273755646,
          "95.0": 2725.9002273755646,
          "99.0": 2725.9002273755646,
          "99.9": 2725.9002273755646,
          "99.99": 2725.9002273755646,
          "99.999": 2725.9002273755646,
          "99.9999": 2725.9002273755646,
          "100.0": 2725.9002273755646
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2588.295098114157,
            2713.0329339846153,
            2716.38432605973,
            2725.9002273755646,
            2691.1335723354864
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "linuxX64Bench": [
    {
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4.412420103565105,
        "scoreError": 0.059717372420043754,
        "scoreConfidence": [
          4.352702731145061,
          4.472137475985149
        ],
        "scorePercentiles": {
          "0.00": 4.353007562734757,
          "25.00": 4.353007562734757,
          "50.00": 4.430399559151462,
          "75.00": 4.453853188809093,
          "90.00": 4.453853188809093,
          "99.00": 4.453853188809093,
          "99.90": 4.453853188809093,
          "99.99": 4.453853188809093,
          "100.00": 4.453853188809093
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            4.353007562734757,
            4.430399559151462,
            4.453853188809093
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4.487954178377287,
        "scoreError": 0.13669717818471266,
        "scoreConfidence": [
          4.351257000192574,
          4.624651356562
        ],
        "scorePercentiles": {
          "0.00": 4.349282314703569,
          "25.00": 4.349282314703569,
          "50.00": 4.54425034111754,
          "75.00": 4.570329879310753,
          "90.00": 4.570329879310753,
          "99.00": 4.570329879310753,
          "99.90": 4.570329879310753,
          "99.99": 4.570329879310753,
          "100.00": 4.570329879310753
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            4.570329879310753,
            4.54425034111754,
            4.349282314703569
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4.1336693134178395,
        "scoreError": 0.041938888601687374,
        "scoreConfidence": [
          4.091730424816152,
          4.175608202019527
        ],
        "scorePercentiles": {
          "0.00": 4.099260941128963,
          "25.00": 4.099260941128963,
          "50.00": 4.128837322285384,
          "75.00": 4.172909676839172,
          "90.00": 4.172909676839172,
          "99.00": 4.172909676839172,
          "99.90": 4.172909676839172,
          "99.99": 4.172909676839172,
          "100.00": 4.172909676839172
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            4.128837322285384,
            4.099260941128963,
            4.172909676839172
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 3.809965086994982,
        "scoreError": 0.18989429158659654,
        "scoreConfidence": [
          3.6200707954083855,
          3.9998593785815784
        ],
        "scorePercentiles": {
          "0.00": 3.633052901614675,
          "25.00": 3.633052901614675,
          "50.00": 3.829962599494462,
          "75.00": 3.9668797598758094,
          "90.00": 3.9668797598758094,
          "99.00": 3.9668797598758094,
          "99.90": 3.9668797598758094,
          "99.99": 3.9668797598758094,
          "100.00": 3.9668797598758094
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            3.9668797598758094,
            3.633052901614675,
            3.829962599494462
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 11.492030988992724,
        "scoreError": 0.29995084883258766,
        "scoreConfidence": [
          11.192080140160137,
          11.791981837825311
        ],
        "scorePercentiles": {
          "0.00": 11.186154658543765,
          "25.00": 11.186154658543765,
          "50.00": 11.635485481249527,
          "75.00": 11.654452827184882,
          "90.00": 11.654452827184882,
          "99.00": 11.654452827184882,
          "99.90": 11.654452827184882,
          "99.99": 11.654452827184882,
          "100.00": 11.654452827184882
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            11.186154658543765,
            11.654452827184882,
            11.635485481249527
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 11.006453828019358,
        "scoreError": 0.0685410773466513,
        "scoreConfidence": [
          10.937912750672707,
          11.07499490536601
        ],
        "scorePercentiles": {
          "0.00": 10.937271730122157,
          "25.00": 10.937271730122157,
          "50.00": 11.03215288238001,
          "75.00": 11.049936871555909,
          "90.00": 11.049936871555909,
          "99.00": 11.049936871555909,
          "99.90": 11.049936871555909,
          "99.99": 11.049936871555909,
          "100.00": 11.049936871555909
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            11.03215288238001,
            10.937271730122157,
            11.049936871555909
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.4627599874456436,
        "scoreError": 0.007922099317583833,
        "scoreConfidence": [
          0.4548378881280598,
          0.4706820867632274
        ],
        "scorePercentiles": {
          "0.00": 0.45808633639332397,
          "25.00": 0.45808633639332397,
          "50.00": 0.4593846942045004,
          "75.00": 0.4708089317391063,
          "90.00": 0.4708089317391063,
          "99.00": 0.4708089317391063,
          "99.90": 0.4708089317391063,
          "99.99": 0.4708089317391063,
          "100.00": 0.4708089317391063
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.4708089317391063,
            0.45808633639332397,
            0.4593846942045004
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.4634217385313042,
        "scoreError": 0.0049998472679548935,
        "scoreConfidence": [
          0.4584218912633493,
          0.4684215857992591
        ],
        "scorePercentiles": {
          "0.00": 0.4597359996149199,
          "25.00": 0.4597359996149199,
          "50.00": 0.4622095434820159,
          "75.00": 0.46831967249697665,
          "90.00": 0.46831967249697665,
          "99.00": 0.46831967249697665,
          "99.90": 0.46831967249697665,
          "99.99": 0.46831967249697665,
          "100.00": 0.46831967249697665
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.46831967249697665,
            0.4597359996149199,
            0.4622095434820159
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.4499727686577705,
        "scoreError": 0.011029602547807682,
        "scoreConfidence": [
          0.43894316610996287,
          0.4610023712055782
        ],
        "scorePercentiles": {
          "0.00": 0.44222158010414886,
          "25.00": 0.44222158010414886,
          "50.00": 0.44678150708472203,
          "75.00": 0.4609152187844406,
          "90.00": 0.4609152187844406,
          "99.00": 0.4609152187844406,
          "99.90": 0.4609152187844406,
          "99.99": 0.4609152187844406,
          "100.00": 0.4609152187844406
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.4609152187844406,
            0.44222158010414886,
            0.44678150708472203
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.48833770668277926,
        "scoreError": 0.010336163274848603,
        "scoreConfidence": [
          0.47800154340793066,
          0.49867386995762786
        ],
        "scorePercentiles": {
          "0.00": 0.47978854523272924,
          "25.00": 0.47978854523272924,
          "50.00": 0.48726299279656055,
          "75.00": 0.49796158201904805,
          "90.00": 0.49796158201904805,
          "99.00": 0.49796158201904805,
          "99.90": 0.49796158201904805,
          "99.99": 0.49796158201904805,
          "100.00": 0.49796158201904805
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.49796158201904805,
            0.47978854523272924,
            0.48726299279656055
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.7466769740019582,
        "scoreError": 0.011475144447080556,
        "scoreConfidence": [
          0.7352018295548777,
          0.7581521184490387
        ],
        "scorePercentiles": {
          "0.00": 0.7353174712383859,
          "25.00": 0.7353174712383859,
          "50.00": 0.7498965224904421,
          "75.00": 0.7548169282770466,
          "90.00": 0.7548169282770466,
          "99.00": 0.7548169282770466,
          "99.90": 0.7548169282770466,
          "99.99": 0.7548169282770466,
          "100.00": 0.7548169282770466
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.7548169282770466,
            0.7498965224904421,
            0.7353174712383859
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.26509998653988875,
        "scoreError": 0.004182888054407512,
        "scoreConfidence": [
          0.2609170984854812,
          0.2692828745942963
        ],
        "scorePercentiles": {
          "0.00": 0.26235238307075465,
          "25.00": 0.26235238307075465,
          "50.00": 0.2636450969014465,
          "75.00": 0.2693024796474651,
          "90.00": 0.2693024796474651,
          "99.00": 0.2693024796474651,
          "99.90": 0.2693024796474651,
          "99.99": 0.2693024796474651,
          "100.00": 0.2693024796474651
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.2636450969014465,
            0.26235238307075465,
            0.2693024796474651
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.43631418758207813,
        "scoreError": 0.0025126161240204893,
        "scoreConfidence": [
          0.43380157145805764,
          0.4388268037060986
        ],
        "scorePercentiles": {
          "0.00": 0.4338602301176608,
          "25.00": 0.4338602301176608,
          "50.00": 0.436897944796979,
          "75.00": 0.43818438783159447,
          "90.00": 0.43818438783159447,
          "99.00": 0.43818438783159447,
          "99.90": 0.43818438783159447,
          "99.99": 0.43818438783159447,
          "100.00": 0.43818438783159447
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.436897944796979,
            0.43818438783159447,
            0.4338602301176608
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.4322308062644122,
        "scoreError": 0.005866026198638323,
        "scoreConfidence": [
          0.4263647800657739,
          0.4380968324630505
        ],
        "scorePercentiles": {
          "0.00": 0.4269635910550718,
          "25.00": 0.4269635910550718,
          "50.00": 0.43240186344037174,
          "75.00": 0.4373269642977929,
          "90.00": 0.4373269642977929,
          "99.00": 0.4373269642977929,
          "99.90": 0.4373269642977929,
          "99.99": 0.4373269642977929,
          "100.00": 0.4373269642977929
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.4269635910550718,
            0.43240186344037174,
            0.4373269642977929
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
