// provided.js - generated by ephemient/aoc2022/Kotlin benchmarks, 2022-12-12 16:36:27.215836000

var providedBenchmarks = ["graalBench","jvmBench","linuxX64Bench"];

var providedBenchmarkStore = {
  "graalBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day10Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 75879.03716076666,
        "scoreError": 3440.460215500298,
        "scoreConfidence": [
          72438.57694526637,
          79319.49737626695
        ],
        "scorePercentiles": {
          "0.0": 74387.07204902223,
          "50.0": 76040.133108368,
          "90.0": 76783.04230178734,
          "95.0": 76783.04230178734,
          "99.0": 76783.04230178734,
          "99.9": 76783.04230178734,
          "99.99": 76783.04230178734,
          "99.999": 76783.04230178734,
          "99.9999": 76783.04230178734,
          "100.0": 76783.04230178734
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            74387.07204902223,
            76783.04230178734,
            76220.84000811035,
            75964.09833654539,
            76040.133108368
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day10Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 60133.46955615516,
        "scoreError": 350.18359579821237,
        "scoreConfidence": [
          59783.28596035695,
          60483.653151953375
        ],
        "scorePercentiles": {
          "0.0": 60044.10294230137,
          "50.0": 60089.93586018859,
          "90.0": 60272.53455494841,
          "95.0": 60272.53455494841,
          "99.0": 60272.53455494841,
          "99.9": 60272.53455494841,
          "99.99": 60272.53455494841,
          "99.999": 60272.53455494841,
          "99.9999": 60272.53455494841,
          "100.0": 60272.53455494841
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            60044.10294230137,
            60089.93586018859,
            60174.2154277829,
            60272.53455494841,
            60086.55899555452
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day11Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 9752.915586007612,
        "scoreError": 59.669619367305195,
        "scoreConfidence": [
          9693.245966640307,
          9812.585205374917
        ],
        "scorePercentiles": {
          "0.0": 9728.094096367104,
          "50.0": 9754.685915364675,
          "90.0": 9766.605983028225,
          "95.0": 9766.605983028225,
          "99.0": 9766.605983028225,
          "99.9": 9766.605983028225,
          "99.99": 9766.605983028225,
          "99.999": 9766.605983028225,
          "99.9999": 9766.605983028225,
          "100.0": 9766.605983028225
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9728.094096367104,
            9766.605983028225,
            9754.685915364675,
            9750.178890837306,
            9765.013044440757
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day11Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 18.41192096216132,
        "scoreError": 0.1367842555056896,
        "scoreConfidence": [
          18.275136706655633,
          18.54870521766701
        ],
        "scorePercentiles": {
          "0.0": 18.366696611728823,
          "50.0": 18.401190875487096,
          "90.0": 18.449410067344164,
          "95.0": 18.449410067344164,
          "99.0": 18.449410067344164,
          "99.9": 18.449410067344164,
          "99.99": 18.449410067344164,
          "99.999": 18.449410067344164,
          "99.9999": 18.449410067344164,
          "100.0": 18.449410067344164
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            18.3955501110063,
            18.401190875487096,
            18.449410067344164,
            18.446757145240213,
            18.366696611728823
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day12Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 546.6666163526248,
        "scoreError": 25.661995282012636,
        "scoreConfidence": [
          521.0046210706122,
          572.3286116346375
        ],
        "scorePercentiles": {
          "0.0": 534.9291042410276,
          "50.0": 548.786880809985,
          "90.0": 551.1644864480065,
          "95.0": 551.1644864480065,
          "99.0": 551.1644864480065,
          "99.9": 551.1644864480065,
          "99.99": 551.1644864480065,
          "99.999": 551.1644864480065,
          "99.9999": 551.1644864480065,
          "100.0": 551.1644864480065
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            534.9291042410276,
            548.786880809985,
            551.1644864480065,
            550.239734858825,
            548.2128754052802
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day12Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 549.6041620599275,
        "scoreError": 8.918394170010389,
        "scoreConfidence": [
          540.6857678899171,
          558.5225562299379
        ],
        "scorePercentiles": {
          "0.0": 547.0431165568637,
          "50.0": 549.7251775411673,
          "90.0": 552.8179885469968,
          "95.0": 552.8179885469968,
          "99.0": 552.8179885469968,
          "99.9": 552.8179885469968,
          "99.99": 552.8179885469968,
          "99.999": 552.8179885469968,
          "99.9999": 552.8179885469968,
          "100.0": 552.8179885469968
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            547.7586307071375,
            552.8179885469968,
            550.6758969474721,
            549.7251775411673,
            547.0431165568637
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5577.855958236333,
        "scoreError": 27.84886702230812,
        "scoreConfidence": [
          5550.007091214025,
          5605.704825258641
        ],
        "scorePercentiles": {
          "0.0": 5572.649111838203,
          "50.0": 5575.233360811021,
          "90.0": 5590.435163709684,
          "95.0": 5590.435163709684,
          "99.0": 5590.435163709684,
          "99.9": 5590.435163709684,
          "99.99": 5590.435163709684,
          "99.999": 5590.435163709684,
          "99.9999": 5590.435163709684,
          "100.0": 5590.435163709684
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5590.435163709684,
            5577.171739802094,
            5572.649111838203,
            5575.233360811021,
            5573.790415020665
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5545.111555636942,
        "scoreError": 12.419238488089626,
        "scoreConfidence": [
          5532.692317148852,
          5557.530794125032
        ],
        "scorePercentiles": {
          "0.0": 5542.395867765622,
          "50.0": 5543.297586791526,
          "90.0": 5549.687448971131,
          "95.0": 5549.687448971131,
          "99.0": 5549.687448971131,
          "99.9": 5549.687448971131,
          "99.99": 5549.687448971131,
          "99.999": 5549.687448971131,
          "99.9999": 5549.687448971131,
          "100.0": 5549.687448971131
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5542.852000735563,
            5547.324873920869,
            5542.395867765622,
            5549.687448971131,
            5543.297586791526
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 12604.227764334039,
        "scoreError": 172.14383573899045,
        "scoreConfidence": [
          12432.083928595048,
          12776.37160007303
        ],
        "scorePercentiles": {
          "0.0": 12525.64720505056,
          "50.0": 12622.543320633169,
          "90.0": 12633.615317860316,
          "95.0": 12633.615317860316,
          "99.0": 12633.615317860316,
          "99.9": 12633.615317860316,
          "99.99": 12633.615317860316,
          "99.999": 12633.615317860316,
          "99.9999": 12633.615317860316,
          "100.0": 12633.615317860316
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            12525.64720505056,
            12622.543320633169,
            12633.615317860316,
            12611.195312728358,
            12628.137665397795
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10790.496348085997,
        "scoreError": 99.76157100321144,
        "scoreConfidence": [
          10690.734777082786,
          10890.257919089208
        ],
        "scorePercentiles": {
          "0.0": 10752.83785162331,
          "50.0": 10802.15607677109,
          "90.0": 10818.503000465813,
          "95.0": 10818.503000465813,
          "99.0": 10818.503000465813,
          "99.9": 10818.503000465813,
          "99.99": 10818.503000465813,
          "99.999": 10818.503000465813,
          "99.9999": 10818.503000465813,
          "100.0": 10818.503000465813
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            10818.503000465813,
            10776.370882131894,
            10802.15607677109,
            10802.613929437879,
            10752.83785162331
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 8890.281280409821,
        "scoreError": 26.1997623105801,
        "scoreConfidence": [
          8864.081518099241,
          8916.481042720401
        ],
        "scorePercentiles": {
          "0.0": 8884.508051216484,
          "50.0": 8888.55124378726,
          "90.0": 8902.06239917987,
          "95.0": 8902.06239917987,
          "99.0": 8902.06239917987,
          "99.9": 8902.06239917987,
          "99.99": 8902.06239917987,
          "99.999": 8902.06239917987,
          "99.9999": 8902.06239917987,
          "100.0": 8902.06239917987
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            8888.55124378726,
            8887.468031585524,
            8888.81667627997,
            8902.06239917987,
            8884.508051216484
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 9568.931740879532,
        "scoreError": 96.22099112854353,
        "scoreConfidence": [
          9472.71074975099,
          9665.152732008075
        ],
        "scorePercentiles": {
          "0.0": 9540.932256346956,
          "50.0": 9566.262460616754,
          "90.0": 9597.610976153865,
          "95.0": 9597.610976153865,
          "99.0": 9597.610976153865,
          "99.9": 9597.610976153865,
          "99.99": 9597.610976153865,
          "99.999": 9597.610976153865,
          "99.9999": 9597.610976153865,
          "100.0": 9597.610976153865
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9540.932256346956,
            9597.610976153865,
            9548.925507157308,
            9590.92750412278,
            9566.262460616754
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1326.6594633458285,
        "scoreError": 103.62970574857323,
        "scoreConfidence": [
          1223.0297575972552,
          1430.2891690944018
        ],
        "scorePercentiles": {
          "0.0": 1293.8937363891116,
          "50.0": 1341.9762559674439,
          "90.0": 1351.5435283371958,
          "95.0": 1351.5435283371958,
          "99.0": 1351.5435283371958,
          "99.9": 1351.5435283371958,
          "99.99": 1351.5435283371958,
          "99.999": 1351.5435283371958,
          "99.9999": 1351.5435283371958,
          "100.0": 1351.5435283371958
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1301.2389664867333,
            1293.8937363891116,
            1341.9762559674439,
            1344.6448295486575,
            1351.5435283371958
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1353.2823995085546,
        "scoreError": 6.21049892740474,
        "scoreConfidence": [
          1347.0719005811497,
          1359.4928984359594
        ],
        "scorePercentiles": {
          "0.0": 1351.0497256649562,
          "50.0": 1353.920294598348,
          "90.0": 1355.0293112026268,
          "95.0": 1355.0293112026268,
          "99.0": 1355.0293112026268,
          "99.9": 1355.0293112026268,
          "99.99": 1355.0293112026268,
          "99.999": 1355.0293112026268,
          "99.9999": 1355.0293112026268,
          "100.0": 1355.0293112026268
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1355.0293112026268,
            1354.1937753190887,
            1352.2188907577538,
            1353.920294598348,
            1351.0497256649562
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2263.081929737839,
        "scoreError": 42.35202458082653,
        "scoreConfidence": [
          2220.7299051570126,
          2305.433954318665
        ],
        "scorePercentiles": {
          "0.0": 2245.060787799667,
          "50.0": 2265.836832661953,
          "90.0": 2274.905206419221,
          "95.0": 2274.905206419221,
          "99.0": 2274.905206419221,
          "99.9": 2274.905206419221,
          "99.99": 2274.905206419221,
          "99.999": 2274.905206419221,
          "99.9999": 2274.905206419221,
          "100.0": 2274.905206419221
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2263.0980535862336,
            2265.836832661953,
            2266.508768222119,
            2274.905206419221,
            2245.060787799667
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2560.3172959882654,
        "scoreError": 2.534442957565182,
        "scoreConfidence": [
          2557.7828530307,
          2562.8517389458307
        ],
        "scorePercentiles": {
          "0.0": 2559.5348301399704,
          "50.0": 2560.506381726483,
          "90.0": 2561.0737876646913,
          "95.0": 2561.0737876646913,
          "99.0": 2561.0737876646913,
          "99.9": 2561.0737876646913,
          "99.99": 2561.0737876646913,
          "99.999": 2561.0737876646913,
          "99.9999": 2561.0737876646913,
          "100.0": 2561.0737876646913
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2560.506381726483,
            2559.7361149348344,
            2559.5348301399704,
            2561.0737876646913,
            2560.735365475348
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2745.889577181247,
        "scoreError": 48.79062898344685,
        "scoreConfidence": [
          2697.0989481978004,
          2794.680206164694
        ],
        "scorePercentiles": {
          "0.0": 2723.330488262774,
          "50.0": 2750.845604891062,
          "90.0": 2753.656336868487,
          "95.0": 2753.656336868487,
          "99.0": 2753.656336868487,
          "99.9": 2753.656336868487,
          "99.99": 2753.656336868487,
          "99.999": 2753.656336868487,
          "99.9999": 2753.656336868487,
          "100.0": 2753.656336868487
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2723.330488262774,
            2753.656336868487,
            2750.9080243088424,
            2750.845604891062,
            2750.7074315750733
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 589.8566776460015,
        "scoreError": 3.589162003283925,
        "scoreConfidence": [
          586.2675156427175,
          593.4458396492854
        ],
        "scorePercentiles": {
          "0.0": 588.6575720037897,
          "50.0": 589.9407766739421,
          "90.0": 590.9422883535178,
          "95.0": 590.9422883535178,
          "99.0": 590.9422883535178,
          "99.9": 590.9422883535178,
          "99.99": 590.9422883535178,
          "99.999": 590.9422883535178,
          "99.9999": 590.9422883535178,
          "100.0": 590.9422883535178
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            590.9422883535178,
            590.5237892153772,
            588.6575720037897,
            589.9407766739421,
            589.2189619833808
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1604.3868166835562,
        "scoreError": 7.92304361973336,
        "scoreConfidence": [
          1596.4637730638228,
          1612.3098603032895
        ],
        "scorePercentiles": {
          "0.0": 1602.5209901101607,
          "50.0": 1603.9575687285924,
          "90.0": 1607.9089256974928,
          "95.0": 1607.9089256974928,
          "99.0": 1607.9089256974928,
          "99.9": 1607.9089256974928,
          "99.99": 1607.9089256974928,
          "99.999": 1607.9089256974928,
          "99.9999": 1607.9089256974928,
          "100.0": 1607.9089256974928
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1602.5209901101607,
            1603.9575687285924,
            1604.0089613204116,
            1603.5376375611233,
            1607.9089256974928
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1601.264811832741,
        "scoreError": 6.781054099252501,
        "scoreConfidence": [
          1594.4837577334886,
          1608.0458659319936
        ],
        "scorePercentiles": {
          "0.0": 1599.0123588234862,
          "50.0": 1601.8653638273558,
          "90.0": 1603.4354078149395,
          "95.0": 1603.4354078149395,
          "99.0": 1603.4354078149395,
          "99.9": 1603.4354078149395,
          "99.99": 1603.4354078149395,
          "99.999": 1603.4354078149395,
          "99.9999": 1603.4354078149395,
          "100.0": 1603.4354078149395
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1603.4354078149395,
            1602.0361253529647,
            1599.9748033449582,
            1601.8653638273558,
            1599.0123588234862
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1038.5780388339565,
        "scoreError": 3.7495483154846183,
        "scoreConfidence": [
          1034.8284905184719,
          1042.3275871494411
        ],
        "scorePercentiles": {
          "0.0": 1037.5061636661935,
          "50.0": 1038.4139898152096,
          "90.0": 1039.915146999753,
          "95.0": 1039.915146999753,
          "99.0": 1039.915146999753,
          "99.9": 1039.915146999753,
          "99.99": 1039.915146999753,
          "99.999": 1039.915146999753,
          "99.9999": 1039.915146999753,
          "100.0": 1039.915146999753
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1038.4139898152096,
            1039.1692870327768,
            1037.8856066558494,
            1039.915146999753,
            1037.5061636661935
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 402.87915212146527,
        "scoreError": 0.8794741580970823,
        "scoreConfidence": [
          401.9996779633682,
          403.75862627956235
        ],
        "scorePercentiles": {
          "0.0": 402.64808356172665,
          "50.0": 402.8177649051489,
          "90.0": 403.21883769423357,
          "95.0": 403.21883769423357,
          "99.0": 403.21883769423357,
          "99.9": 403.21883769423357,
          "99.99": 403.21883769423357,
          "99.999": 403.21883769423357,
          "99.9999": 403.21883769423357,
          "100.0": 403.21883769423357
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            402.64808356172665,
            402.8177649051489,
            402.987819925559,
            402.72325452065826,
            403.21883769423357
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 666.919991694523,
        "scoreError": 135.87817732550474,
        "scoreConfidence": [
          531.0418143690183,
          802.7981690200277
        ],
        "scorePercentiles": {
          "0.0": 639.7045084893384,
          "50.0": 643.7232395615526,
          "90.0": 708.0446459798491,
          "95.0": 708.0446459798491,
          "99.0": 708.0446459798491,
          "99.9": 708.0446459798491,
          "99.99": 708.0446459798491,
          "99.999": 708.0446459798491,
          "99.9999": 708.0446459798491,
          "100.0": 708.0446459798491
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            639.7045084893384,
            640.1982924822903,
            643.7232395615526,
            702.9292719595848,
            708.0446459798491
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 360.46874401252114,
        "scoreError": 13.29861122540784,
        "scoreConfidence": [
          347.1701327871133,
          373.767355237929
        ],
        "scorePercentiles": {
          "0.0": 358.1539086670899,
          "50.0": 359.2590096112084,
          "90.0": 366.58726892518615,
          "95.0": 366.58726892518615,
          "99.0": 366.58726892518615,
          "99.9": 366.58726892518615,
          "99.99": 366.58726892518615,
          "99.999": 366.58726892518615,
          "99.9999": 366.58726892518615,
          "100.0": 366.58726892518615
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            366.58726892518615,
            358.1539086670899,
            359.2590096112084,
            358.96315279132915,
            359.3803800677922
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvmBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day10Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 229417.9292933101,
        "scoreError": 4766.089007088882,
        "scoreConfidence": [
          224651.8402862212,
          234184.01830039898
        ],
        "scorePercentiles": {
          "0.0": 227240.3619274138,
          "50.0": 230036.68286707363,
          "90.0": 230151.91683287214,
          "95.0": 230151.91683287214,
          "99.0": 230151.91683287214,
          "99.9": 230151.91683287214,
          "99.99": 230151.91683287214,
          "99.999": 230151.91683287214,
          "99.9999": 230151.91683287214,
          "100.0": 230151.91683287214
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            227240.3619274138,
            229580.92238536666,
            230036.68286707363,
            230151.91683287214,
            230079.76245382402
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day10Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 159070.6154994754,
        "scoreError": 2349.634233220334,
        "scoreConfidence": [
          156720.98126625505,
          161420.24973269572
        ],
        "scorePercentiles": {
          "0.0": 158199.52091098964,
          "50.0": 158954.54202264966,
          "90.0": 159738.41325624113,
          "95.0": 159738.41325624113,
          "99.0": 159738.41325624113,
          "99.9": 159738.41325624113,
          "99.99": 159738.41325624113,
          "99.999": 159738.41325624113,
          "99.9999": 159738.41325624113,
          "100.0": 159738.41325624113
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            158199.52091098964,
            159562.04484082854,
            158898.556466668,
            158954.54202264966,
            159738.41325624113
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day11Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 17339.725305120584,
        "scoreError": 167.53641577363052,
        "scoreConfidence": [
          17172.188889346955,
          17507.261720894214
        ],
        "scorePercentiles": {
          "0.0": 17284.613629102478,
          "50.0": 17323.980897876983,
          "90.0": 17391.76370517541,
          "95.0": 17391.76370517541,
          "99.0": 17391.76370517541,
          "99.9": 17391.76370517541,
          "99.99": 17391.76370517541,
          "99.999": 17391.76370517541,
          "99.9999": 17391.76370517541,
          "100.0": 17391.76370517541
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            17323.980897876983,
            17375.60855301077,
            17391.76370517541,
            17322.659740437266,
            17284.613629102478
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day11Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 33.9191848035397,
        "scoreError": 0.5164321181283013,
        "scoreConfidence": [
          33.4027526854114,
          34.435616921668
        ],
        "scorePercentiles": {
          "0.0": 33.771297195633665,
          "50.0": 33.90183915036458,
          "90.0": 34.057545136525384,
          "95.0": 34.057545136525384,
          "99.0": 34.057545136525384,
          "99.9": 34.057545136525384,
          "99.99": 34.057545136525384,
          "99.999": 34.057545136525384,
          "99.9999": 34.057545136525384,
          "100.0": 34.057545136525384
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            33.90183915036458,
            33.771297195633665,
            34.057545136525384,
            34.05564950784896,
            33.80959302732592
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day12Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 922.4005882899171,
        "scoreError": 17.92263354396834,
        "scoreConfidence": [
          904.4779547459488,
          940.3232218338854
        ],
        "scorePercentiles": {
          "0.0": 914.1104875946916,
          "50.0": 924.2291879666062,
          "90.0": 925.0462054356215,
          "95.0": 925.0462054356215,
          "99.0": 925.0462054356215,
          "99.9": 925.0462054356215,
          "99.99": 925.0462054356215,
          "99.999": 925.0462054356215,
          "99.9999": 925.0462054356215,
          "100.0": 925.0462054356215
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            914.1104875946916,
            923.9171635408271,
            924.2291879666062,
            925.0462054356215,
            924.6998969118391
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day12Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 883.4004363440445,
        "scoreError": 25.654387599493216,
        "scoreConfidence": [
          857.7460487445512,
          909.0548239435377
        ],
        "scorePercentiles": {
          "0.0": 871.6326556470734,
          "50.0": 886.1915425210143,
          "90.0": 887.401607348133,
          "95.0": 887.401607348133,
          "99.0": 887.401607348133,
          "99.9": 887.401607348133,
          "99.99": 887.401607348133,
          "99.999": 887.401607348133,
          "99.9999": 887.401607348133,
          "100.0": 887.401607348133
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            871.6326556470734,
            884.6860651407391,
            887.0903110632624,
            887.401607348133,
            886.1915425210143
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 28534.71039307393,
        "scoreError": 269.89890741588084,
        "scoreConfidence": [
          28264.811485658047,
          28804.60930048981
        ],
        "scorePercentiles": {
          "0.0": 28418.96714363633,
          "50.0": 28542.159852187007,
          "90.0": 28592.146684715914,
          "95.0": 28592.146684715914,
          "99.0": 28592.146684715914,
          "99.9": 28592.146684715914,
          "99.99": 28592.146684715914,
          "99.999": 28592.146684715914,
          "99.9999": 28592.146684715914,
          "100.0": 28592.146684715914
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            28418.96714363633,
            28531.79018047459,
            28542.159852187007,
            28588.488104355798,
            28592.146684715914
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 28228.466667794168,
        "scoreError": 342.6628654856654,
        "scoreConfidence": [
          27885.803802308503,
          28571.129533279833
        ],
        "scorePercentiles": {
          "0.0": 28082.74928778872,
          "50.0": 28266.51245130728,
          "90.0": 28313.33507846441,
          "95.0": 28313.33507846441,
          "99.0": 28313.33507846441,
          "99.9": 28313.33507846441,
          "99.99": 28313.33507846441,
          "99.999": 28313.33507846441,
          "99.9999": 28313.33507846441,
          "100.0": 28313.33507846441
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            28082.74928778872,
            28212.19059485027,
            28267.545926560164,
            28266.51245130728,
            28313.33507846441
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 30766.338756317302,
        "scoreError": 778.8265721052733,
        "scoreConfidence": [
          29987.512184212028,
          31545.165328422576
        ],
        "scorePercentiles": {
          "0.0": 30414.239746025713,
          "50.0": 30841.132367795417,
          "90.0": 30905.11986523744,
          "95.0": 30905.11986523744,
          "99.0": 30905.11986523744,
          "99.9": 30905.11986523744,
          "99.99": 30905.11986523744,
          "99.999": 30905.11986523744,
          "99.9999": 30905.11986523744,
          "100.0": 30905.11986523744
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            30414.239746025713,
            30886.649826272027,
            30784.551976255898,
            30905.11986523744,
            30841.132367795417
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 23759.65380169196,
        "scoreError": 904.6212676031406,
        "scoreConfidence": [
          22855.03253408882,
          24664.275069295098
        ],
        "scorePercentiles": {
          "0.0": 23438.16190364883,
          "50.0": 23827.411657477445,
          "90.0": 24020.360645182132,
          "95.0": 24020.360645182132,
          "99.0": 24020.360645182132,
          "99.9": 24020.360645182132,
          "99.99": 24020.360645182132,
          "99.999": 24020.360645182132,
          "99.9999": 24020.360645182132,
          "100.0": 24020.360645182132
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            23438.16190364883,
            23606.46310278642,
            23905.87169936494,
            23827.411657477445,
            24020.360645182132
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 28963.310483804846,
        "scoreError": 25698.235748488503,
        "scoreConfidence": [
          3265.0747353163424,
          54661.546232293345
        ],
        "scorePercentiles": {
          "0.0": 23531.41066897723,
          "50.0": 24417.49296432052,
          "90.0": 36956.59648502615,
          "95.0": 36956.59648502615,
          "99.0": 36956.59648502615,
          "99.9": 36956.59648502615,
          "99.99": 36956.59648502615,
          "99.999": 36956.59648502615,
          "99.9999": 36956.59648502615,
          "100.0": 36956.59648502615
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            35528.863134999556,
            36956.59648502615,
            23531.41066897723,
            24417.49296432052,
            24382.18916570077
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 60936.31718948776,
        "scoreError": 543.2659449544359,
        "scoreConfidence": [
          60393.05124453332,
          61479.5831344422
        ],
        "scorePercentiles": {
          "0.0": 60734.13051428616,
          "50.0": 60933.590335523186,
          "90.0": 61125.4985905529,
          "95.0": 61125.4985905529,
          "99.0": 61125.4985905529,
          "99.9": 61125.4985905529,
          "99.99": 61125.4985905529,
          "99.999": 61125.4985905529,
          "99.9999": 61125.4985905529,
          "100.0": 61125.4985905529
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            60734.13051428616,
            60933.590335523186,
            60906.63969336448,
            60981.72681371207,
            61125.4985905529
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5261.093788619706,
        "scoreError": 57.82699552639029,
        "scoreConfidence": [
          5203.266793093316,
          5318.920784146097
        ],
        "scorePercentiles": {
          "0.0": 5234.636608230663,
          "50.0": 5268.742356468253,
          "90.0": 5269.910756574618,
          "95.0": 5269.910756574618,
          "99.0": 5269.910756574618,
          "99.9": 5269.910756574618,
          "99.99": 5269.910756574618,
          "99.999": 5269.910756574618,
          "99.9999": 5269.910756574618,
          "100.0": 5269.910756574618
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5234.636608230663,
            5263.264607697675,
            5268.742356468253,
            5268.914614127319,
            5269.910756574618
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5259.282694684029,
        "scoreError": 70.88004744291534,
        "scoreConfidence": [
          5188.402647241113,
          5330.162742126944
        ],
        "scorePercentiles": {
          "0.0": 5231.572681641657,
          "50.0": 5259.93279907057,
          "90.0": 5282.858173304315,
          "95.0": 5282.858173304315,
          "99.0": 5282.858173304315,
          "99.9": 5282.858173304315,
          "99.99": 5282.858173304315,
          "99.999": 5282.858173304315,
          "99.9999": 5282.858173304315,
          "100.0": 5282.858173304315
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5231.572681641657,
            5264.572931487935,
            5259.93279907057,
            5282.858173304315,
            5257.476887915664
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 6460.1484536503895,
        "scoreError": 277.4534488058904,
        "scoreConfidence": [
          6182.695004844499,
          6737.60190245628
        ],
        "scorePercentiles": {
          "0.0": 6376.882992347107,
          "50.0": 6484.461350420384,
          "90.0": 6531.628623758452,
          "95.0": 6531.628623758452,
          "99.0": 6531.628623758452,
          "99.9": 6531.628623758452,
          "99.99": 6531.628623758452,
          "99.999": 6531.628623758452,
          "99.9999": 6531.628623758452,
          "100.0": 6531.628623758452
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            6390.422656595303,
            6517.346645130701,
            6376.882992347107,
            6484.461350420384,
            6531.628623758452
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7518.8158987369225,
        "scoreError": 211.38100113673096,
        "scoreConfidence": [
          7307.434897600191,
          7730.196899873654
        ],
        "scorePercentiles": {
          "0.0": 7423.868745377348,
          "50.0": 7541.794504011527,
          "90.0": 7562.864255244884,
          "95.0": 7562.864255244884,
          "99.0": 7562.864255244884,
          "99.9": 7562.864255244884,
          "99.99": 7562.864255244884,
          "99.999": 7562.864255244884,
          "99.9999": 7562.864255244884,
          "100.0": 7562.864255244884
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7423.868745377348,
            7523.267353472377,
            7541.794504011527,
            7562.864255244884,
            7542.284635578477
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5099.686301225461,
        "scoreError": 37.22957616671307,
        "scoreConfidence": [
          5062.456725058748,
          5136.915877392174
        ],
        "scorePercentiles": {
          "0.0": 5082.830686455993,
          "50.0": 5102.539816385824,
          "90.0": 5107.5680013745905,
          "95.0": 5107.5680013745905,
          "99.0": 5107.5680013745905,
          "99.9": 5107.5680013745905,
          "99.99": 5107.5680013745905,
          "99.999": 5107.5680013745905,
          "99.9999": 5107.5680013745905,
          "100.0": 5107.5680013745905
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5082.830686455993,
            5102.539816385824,
            5107.5680013745905,
            5103.381679379108,
            5102.1113225317895
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1007.1744443070944,
        "scoreError": 20.01033047548383,
        "scoreConfidence": [
          987.1641138316106,
          1027.1847747825782
        ],
        "scorePercentiles": {
          "0.0": 1000.1083803764017,
          "50.0": 1007.9385348892155,
          "90.0": 1014.2565621110514,
          "95.0": 1014.2565621110514,
          "99.0": 1014.2565621110514,
          "99.9": 1014.2565621110514,
          "99.99": 1014.2565621110514,
          "99.999": 1014.2565621110514,
          "99.9999": 1014.2565621110514,
          "100.0": 1014.2565621110514
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1000.1083803764017,
            1004.9074585815854,
            1008.6612855772175,
            1007.9385348892155,
            1014.2565621110514
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3818.9225475490775,
        "scoreError": 227.2471013472516,
        "scoreConfidence": [
          3591.675446201826,
          4046.169648896329
        ],
        "scorePercentiles": {
          "0.0": 3721.388536195233,
          "50.0": 3848.1898439736788,
          "90.0": 3861.386569819826,
          "95.0": 3861.386569819826,
          "99.0": 3861.386569819826,
          "99.9": 3861.386569819826,
          "99.99": 3861.386569819826,
          "99.999": 3861.386569819826,
          "99.9999": 3861.386569819826,
          "100.0": 3861.386569819826
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3721.388536195233,
            3805.1245892318766,
            3858.523198524774,
            3848.1898439736788,
            3861.386569819826
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4024.013195208703,
        "scoreError": 71.72376006138293,
        "scoreConfidence": [
          3952.28943514732,
          4095.736955270086
        ],
        "scorePercentiles": {
          "0.0": 3993.05676226644,
          "50.0": 4027.389598265959,
          "90.0": 4043.471270708995,
          "95.0": 4043.471270708995,
          "99.0": 4043.471270708995,
          "99.9": 4043.471270708995,
          "99.99": 4043.471270708995,
          "99.999": 4043.471270708995,
          "99.9999": 4043.471270708995,
          "100.0": 4043.471270708995
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3993.05676226644,
            4029.873529452312,
            4027.389598265959,
            4026.2748153498073,
            4043.471270708995
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2379.296336728028,
        "scoreError": 11.840878451112841,
        "scoreConfidence": [
          2367.455458276915,
          2391.137215179141
        ],
        "scorePercentiles": {
          "0.0": 2374.257683586711,
          "50.0": 2380.990084007947,
          "90.0": 2381.6973898326482,
          "95.0": 2381.6973898326482,
          "99.0": 2381.6973898326482,
          "99.9": 2381.6973898326482,
          "99.99": 2381.6973898326482,
          "99.999": 2381.6973898326482,
          "99.9999": 2381.6973898326482,
          "100.0": 2381.6973898326482
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2374.257683586711,
            2381.0636699012143,
            2380.990084007947,
            2381.6973898326482,
            2378.472856311621
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 943.8032649664186,
        "scoreError": 5.1461457011603455,
        "scoreConfidence": [
          938.6571192652583,
          948.949410667579
        ],
        "scorePercentiles": {
          "0.0": 942.5683894513547,
          "50.0": 944.007054675603,
          "90.0": 945.8226629798046,
          "95.0": 945.8226629798046,
          "99.0": 945.8226629798046,
          "99.9": 945.8226629798046,
          "99.99": 945.8226629798046,
          "99.999": 945.8226629798046,
          "99.9999": 945.8226629798046,
          "100.0": 945.8226629798046
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            944.007054675603,
            942.59795970991,
            944.0202580154213,
            942.5683894513547,
            945.8226629798046
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 977.5825454218011,
        "scoreError": 7.72438782203624,
        "scoreConfidence": [
          969.8581575997649,
          985.3069332438373
        ],
        "scorePercentiles": {
          "0.0": 974.5747551286662,
          "50.0": 977.9213929498763,
          "90.0": 979.9045568566535,
          "95.0": 979.9045568566535,
          "99.0": 979.9045568566535,
          "99.9": 979.9045568566535,
          "99.99": 979.9045568566535,
          "99.999": 979.9045568566535,
          "99.9999": 979.9045568566535,
          "100.0": 979.9045568566535
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            974.5747551286662,
            977.9213929498763,
            979.9045568566535,
            976.8950262206815,
            978.6169959531281
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 582.1332763498347,
        "scoreError": 8.792384830681145,
        "scoreConfidence": [
          573.3408915191535,
          590.9256611805158
        ],
        "scorePercentiles": {
          "0.0": 579.8095026598068,
          "50.0": 582.3422397814289,
          "90.0": 585.0589899504457,
          "95.0": 585.0589899504457,
          "99.0": 585.0589899504457,
          "99.9": 585.0589899504457,
          "99.99": 585.0589899504457,
          "99.999": 585.0589899504457,
          "99.9999": 585.0589899504457,
          "100.0": 585.0589899504457
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            579.9219097379265,
            579.8095026598068,
            582.3422397814289,
            583.5337396195655,
            585.0589899504457
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "linuxX64Bench": [
    {
      "benchmark": "com.github.ephemient.aoc2022.Day10Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 51525.877542525006,
        "scoreError": 462.49907609461025,
        "scoreConfidence": [
          51063.3784664304,
          51988.376618619615
        ],
        "scorePercentiles": {
          "0.00": 51067.10787194649,
          "25.00": 51067.10787194649,
          "50.00": 51659.38860401115,
          "75.00": 51851.13615161739,
          "90.00": 51851.13615161739,
          "99.00": 51851.13615161739,
          "99.90": 51851.13615161739,
          "99.99": 51851.13615161739,
          "100.00": 51851.13615161739
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            51851.13615161739,
            51659.38860401115,
            51067.10787194649
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day10Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 43115.13960557012,
        "scoreError": 346.10757553213995,
        "scoreConfidence": [
          42769.032030037975,
          43461.24718110226
        ],
        "scorePercentiles": {
          "0.00": 42835.240787081464,
          "25.00": 42835.240787081464,
          "50.00": 43068.56876773103,
          "75.00": 43441.609261897866,
          "90.00": 43441.609261897866,
          "99.00": 43441.609261897866,
          "99.90": 43441.609261897866,
          "99.99": 43441.609261897866,
          "100.00": 43441.609261897866
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            43441.609261897866,
            43068.56876773103,
            42835.240787081464
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day11Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4862.719742074886,
        "scoreError": 28.587778618016415,
        "scoreConfidence": [
          4834.13196345687,
          4891.3075206929025
        ],
        "scorePercentiles": {
          "0.00": 4845.802242613355,
          "25.00": 4845.802242613355,
          "50.00": 4850.597725105874,
          "75.00": 4891.759258505431,
          "90.00": 4891.759258505431,
          "99.00": 4891.759258505431,
          "99.90": 4891.759258505431,
          "99.99": 4891.759258505431,
          "100.00": 4891.759258505431
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            4891.759258505431,
            4850.597725105874,
            4845.802242613355
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day11Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 6.671528249533567,
        "scoreError": 0.01638048831889093,
        "scoreConfidence": [
          6.655147761214676,
          6.6879087378524575
        ],
        "scorePercentiles": {
          "0.00": 6.657073886596785,
          "25.00": 6.657073886596785,
          "50.00": 6.6714862118440665,
          "75.00": 6.686024650159849,
          "90.00": 6.686024650159849,
          "99.00": 6.686024650159849,
          "99.90": 6.686024650159849,
          "99.99": 6.686024650159849,
          "100.00": 6.686024650159849
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            6.657073886596785,
            6.686024650159849,
            6.6714862118440665
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day12Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 210.28451405230783,
        "scoreError": 2.7771245896653087,
        "scoreConfidence": [
          207.50738946264252,
          213.06163864197313
        ],
        "scorePercentiles": {
          "0.00": 208.47622737935063,
          "25.00": 208.47622737935063,
          "50.00": 209.2991088001157,
          "75.00": 213.07820597745715,
          "90.00": 213.07820597745715,
          "99.00": 213.07820597745715,
          "99.90": 213.07820597745715,
          "99.99": 213.07820597745715,
          "100.00": 213.07820597745715
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            213.07820597745715,
            209.2991088001157,
            208.47622737935063
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day12Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 210.22874457253536,
        "scoreError": 0.878995840106712,
        "scoreConfidence": [
          209.34974873242865,
          211.10774041264207
        ],
        "scorePercentiles": {
          "0.00": 209.69090392220048,
          "25.00": 209.69090392220048,
          "50.00": 209.87604263262904,
          "75.00": 211.1192871627766,
          "90.00": 211.1192871627766,
          "99.00": 211.1192871627766,
          "99.90": 211.1192871627766,
          "99.99": 211.1192871627766,
          "100.00": 211.1192871627766
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            211.1192871627766,
            209.69090392220048,
            209.87604263262904
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5923.974395902092,
        "scoreError": 43.3153173035971,
        "scoreConfidence": [
          5880.6590785984945,
          5967.289713205689
        ],
        "scorePercentiles": {
          "0.00": 5886.738681491766,
          "25.00": 5886.738681491766,
          "50.00": 5921.969207911963,
          "75.00": 5963.2152983025435,
          "90.00": 5963.2152983025435,
          "99.00": 5963.2152983025435,
          "99.90": 5963.2152983025435,
          "99.99": 5963.2152983025435,
          "100.00": 5963.2152983025435
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5963.2152983025435,
            5921.969207911963,
            5886.738681491766
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5726.036295644208,
        "scoreError": 47.65406849793922,
        "scoreConfidence": [
          5678.382227146269,
          5773.690364142147
        ],
        "scorePercentiles": {
          "0.00": 5687.578564893261,
          "25.00": 5687.578564893261,
          "50.00": 5719.493821961601,
          "75.00": 5771.036500077763,
          "90.00": 5771.036500077763,
          "99.00": 5771.036500077763,
          "99.90": 5771.036500077763,
          "99.99": 5771.036500077763,
          "100.00": 5771.036500077763
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5771.036500077763,
            5719.493821961601,
            5687.578564893261
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5554.229118852294,
        "scoreError": 60.15885169301167,
        "scoreConfidence": [
          5494.070267159283,
          5614.3879705453055
        ],
        "scorePercentiles": {
          "0.00": 5513.724821387921,
          "25.00": 5513.724821387921,
          "50.00": 5534.533978844581,
          "75.00": 5614.4285563243775,
          "90.00": 5614.4285563243775,
          "99.00": 5614.4285563243775,
          "99.90": 5614.4285563243775,
          "99.99": 5614.4285563243775,
          "100.00": 5614.4285563243775
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5614.4285563243775,
            5534.533978844581,
            5513.724821387921
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5473.604820087107,
        "scoreError": 64.03080391996717,
        "scoreConfidence": [
          5409.57401616714,
          5537.6356240070745
        ],
        "scorePercentiles": {
          "0.00": 5419.404213901758,
          "25.00": 5419.404213901758,
          "50.00": 5469.106582250082,
          "75.00": 5532.303664109481,
          "90.00": 5532.303664109481,
          "99.00": 5532.303664109481,
          "99.90": 5532.303664109481,
          "99.99": 5532.303664109481,
          "100.00": 5532.303664109481
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5532.303664109481,
            5469.106582250082,
            5419.404213901758
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 14949.818632465709,
        "scoreError": 88.17877686372904,
        "scoreConfidence": [
          14861.63985560198,
          15037.997409329439
        ],
        "scorePercentiles": {
          "0.00": 14902.929664627765,
          "25.00": 14902.929664627765,
          "50.00": 14906.756385313594,
          "75.00": 15039.769847455767,
          "90.00": 15039.769847455767,
          "99.00": 15039.769847455767,
          "99.90": 15039.769847455767,
          "99.99": 15039.769847455767,
          "100.00": 15039.769847455767
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            14902.929664627765,
            15039.769847455767,
            14906.756385313594
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 14568.44346109306,
        "scoreError": 51.299748866539055,
        "scoreConfidence": [
          14517.143712226522,
          14619.743209959599
        ],
        "scorePercentiles": {
          "0.00": 14519.544456140971,
          "25.00": 14519.544456140971,
          "50.00": 14576.712825624276,
          "75.00": 14609.073101513934,
          "90.00": 14609.073101513934,
          "99.00": 14609.073101513934,
          "99.90": 14609.073101513934,
          "99.99": 14609.073101513934,
          "100.00": 14609.073101513934
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            14609.073101513934,
            14576.712825624276,
            14519.544456140971
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 598.6491130713489,
        "scoreError": 3.8302668680697507,
        "scoreConfidence": [
          594.8188462032791,
          602.4793799394187
        ],
        "scorePercentiles": {
          "0.00": 594.7801373871067,
          "25.00": 594.7801373871067,
          "50.00": 600.103838601133,
          "75.00": 601.0633632258069,
          "90.00": 601.0633632258069,
          "99.00": 601.0633632258069,
          "99.90": 601.0633632258069,
          "99.99": 601.0633632258069,
          "100.00": 601.0633632258069
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            601.0633632258069,
            600.103838601133,
            594.7801373871067
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 591.8871917146271,
        "scoreError": 3.039688687944228,
        "scoreConfidence": [
          588.8475030266828,
          594.9268804025713
        ],
        "scorePercentiles": {
          "0.00": 590.1955261176574,
          "25.00": 590.1955261176574,
          "50.00": 590.4815326721451,
          "75.00": 594.9845163540784,
          "90.00": 594.9845163540784,
          "99.00": 594.9845163540784,
          "99.90": 594.9845163540784,
          "99.99": 594.9845163540784,
          "100.00": 594.9845163540784
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            594.9845163540784,
            590.4815326721451,
            590.1955261176574
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 583.8210984556341,
        "scoreError": 0.7520784930006879,
        "scoreConfidence": [
          583.0690199626334,
          584.5731769486348
        ],
        "scorePercentiles": {
          "0.00": 583.3824263227525,
          "25.00": 583.3824263227525,
          "50.00": 583.4951059432482,
          "75.00": 584.5857631009018,
          "90.00": 584.5857631009018,
          "99.00": 584.5857631009018,
          "99.90": 584.5857631009018,
          "99.99": 584.5857631009018,
          "100.00": 584.5857631009018
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            583.4951059432482,
            584.5857631009018,
            583.3824263227525
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 590.6713486107875,
        "scoreError": 4.52726785086994,
        "scoreConfidence": [
          586.1440807599175,
          595.1986164616575
        ],
        "scorePercentiles": {
          "0.00": 587.0424001654161,
          "25.00": 587.0424001654161,
          "50.00": 590.0101408662301,
          "75.00": 594.9615048007164,
          "90.00": 594.9615048007164,
          "99.00": 594.9615048007164,
          "99.90": 594.9615048007164,
          "99.99": 594.9615048007164,
          "100.00": 594.9615048007164
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            594.9615048007164,
            590.0101408662301,
            587.0424001654161
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 983.7543947168706,
        "scoreError": 9.859129614636064,
        "scoreConfidence": [
          973.8952651022345,
          993.6135243315067
        ],
        "scorePercentiles": {
          "0.00": 975.0966869662308,
          "25.00": 975.0966869662308,
          "50.00": 983.6458115102773,
          "75.00": 992.5206856741039,
          "90.00": 992.5206856741039,
          "99.00": 992.5206856741039,
          "99.90": 992.5206856741039,
          "99.99": 992.5206856741039,
          "100.00": 992.5206856741039
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            983.6458115102773,
            992.5206856741039,
            975.0966869662308
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 348.2644587887828,
        "scoreError": 3.712549510813857,
        "scoreConfidence": [
          344.55190927796895,
          351.97700829959666
        ],
        "scorePercentiles": {
          "0.00": 345.75342460845565,
          "25.00": 345.75342460845565,
          "50.00": 347.063447207264,
          "75.00": 351.9765045506287,
          "90.00": 351.9765045506287,
          "99.00": 351.9765045506287,
          "99.90": 351.9765045506287,
          "99.99": 351.9765045506287,
          "100.00": 351.9765045506287
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            351.9765045506287,
            345.75342460845565,
            347.063447207264
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 599.4020329483484,
        "scoreError": 5.5577711255001345,
        "scoreConfidence": [
          593.8442618228482,
          604.9598040738485
        ],
        "scorePercentiles": {
          "0.00": 595.827848392196,
          "25.00": 595.827848392196,
          "50.00": 597.3758925641956,
          "75.00": 605.0023578886538,
          "90.00": 605.0023578886538,
          "99.00": 605.0023578886538,
          "99.90": 605.0023578886538,
          "99.99": 605.0023578886538,
          "100.00": 605.0023578886538
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            605.0023578886538,
            595.827848392196,
            597.3758925641956
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 602.7957875393842,
        "scoreError": 6.849281808022076,
        "scoreConfidence": [
          595.9465057313621,
          609.6450693474062
        ],
        "scorePercentiles": {
          "0.00": 595.8733307620182,
          "25.00": 595.8733307620182,
          "50.00": 605.4233816765693,
          "75.00": 607.0906501795652,
          "90.00": 607.0906501795652,
          "99.00": 607.0906501795652,
          "99.90": 607.0906501795652,
          "99.99": 607.0906501795652,
          "100.00": 607.0906501795652
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            607.0906501795652,
            605.4233816765693,
            595.8733307620182
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 1293.0834575967242,
        "scoreError": 1.1503349894158743,
        "scoreConfidence": [
          1291.9331226073084,
          1294.23379258614
        ],
        "scorePercentiles": {
          "0.00": 1292.2227215718608,
          "25.00": 1292.2227215718608,
          "50.00": 1292.822649296147,
          "75.00": 1294.2050019221647,
          "90.00": 1294.2050019221647,
          "99.00": 1294.2050019221647,
          "99.90": 1294.2050019221647,
          "99.99": 1294.2050019221647,
          "100.00": 1294.2050019221647
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            1294.2050019221647,
            1292.2227215718608,
            1292.822649296147
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 347.3283079365228,
        "scoreError": 1.24980131096491,
        "scoreConfidence": [
          346.07850662555785,
          348.5781092474877
        ],
        "scorePercentiles": {
          "0.00": 346.5620495379988,
          "25.00": 346.5620495379988,
          "50.00": 346.82857650777527,
          "75.00": 348.5942977637942,
          "90.00": 348.5942977637942,
          "99.00": 348.5942977637942,
          "99.90": 348.5942977637942,
          "99.99": 348.5942977637942,
          "100.00": 348.5942977637942
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            348.5942977637942,
            346.82857650777527,
            346.5620495379988
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 322.52350658418305,
        "scoreError": 2.0129587153255297,
        "scoreConfidence": [
          320.51054786885754,
          324.53646529950856
        ],
        "scorePercentiles": {
          "0.00": 321.0124550731396,
          "25.00": 321.0124550731396,
          "50.00": 322.07410445155415,
          "75.00": 324.4839602278555,
          "90.00": 324.4839602278555,
          "99.00": 324.4839602278555,
          "99.90": 324.4839602278555,
          "99.99": 324.4839602278555,
          "100.00": 324.4839602278555
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            322.07410445155415,
            321.0124550731396,
            324.4839602278555
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 135.12687147390545,
        "scoreError": 1.2008857420687529,
        "scoreConfidence": [
          133.9259857318367,
          136.3277572159742
        ],
        "scorePercentiles": {
          "0.00": 133.90211634783068,
          "25.00": 133.90211634783068,
          "50.00": 135.70499566567358,
          "75.00": 135.77350240821207,
          "90.00": 135.77350240821207,
          "99.00": 135.77350240821207,
          "99.90": 135.77350240821207,
          "99.99": 135.77350240821207,
          "100.00": 135.77350240821207
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            135.70499566567358,
            135.77350240821207,
            133.90211634783068
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
