// provided.js - generated by ephemient/aoc2022/Kotlin benchmarks, 2022-12-09 06:39:50.773579789

var providedBenchmarks = ["graalBench","jvmBench","linuxX64Bench"];

var providedBenchmarkStore = {
  "graalBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4866.716043603218,
        "scoreError": 752.1779857996072,
        "scoreConfidence": [
          4114.538057803611,
          5618.894029402825
        ],
        "scorePercentiles": {
          "0.0": 4576.230959810973,
          "50.0": 4973.925112217663,
          "90.0": 5029.178667857899,
          "95.0": 5029.178667857899,
          "99.0": 5029.178667857899,
          "99.9": 5029.178667857899,
          "99.99": 5029.178667857899,
          "99.999": 5029.178667857899,
          "99.9999": 5029.178667857899,
          "100.0": 5029.178667857899
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4576.230959810973,
            4754.35867292741,
            4973.925112217663,
            5029.178667857899,
            4999.886805202143
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4997.887729835012,
        "scoreError": 121.51583050066914,
        "scoreConfidence": [
          4876.371899334343,
          5119.403560335681
        ],
        "scorePercentiles": {
          "0.0": 4954.116217124903,
          "50.0": 4997.25573287272,
          "90.0": 5037.9206557270345,
          "95.0": 5037.9206557270345,
          "99.0": 5037.9206557270345,
          "99.9": 5037.9206557270345,
          "99.99": 5037.9206557270345,
          "99.999": 5037.9206557270345,
          "99.9999": 5037.9206557270345,
          "100.0": 5037.9206557270345
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5015.154725761901,
            4984.991317688503,
            4954.116217124903,
            4997.25573287272,
            5037.9206557270345
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 11298.203025777879,
        "scoreError": 285.5091789979722,
        "scoreConfidence": [
          11012.693846779906,
          11583.712204775851
        ],
        "scorePercentiles": {
          "0.0": 11193.087109465107,
          "50.0": 11309.343695280884,
          "90.0": 11372.879776768976,
          "95.0": 11372.879776768976,
          "99.0": 11372.879776768976,
          "99.9": 11372.879776768976,
          "99.99": 11372.879776768976,
          "99.999": 11372.879776768976,
          "99.9999": 11372.879776768976,
          "100.0": 11372.879776768976
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            11193.087109465107,
            11372.879776768976,
            11309.343695280884,
            11257.582445636319,
            11358.122101738105
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10129.679073185263,
        "scoreError": 73.04285110302348,
        "scoreConfidence": [
          10056.63622208224,
          10202.721924288287
        ],
        "scorePercentiles": {
          "0.0": 10110.35809806559,
          "50.0": 10123.690436501021,
          "90.0": 10152.034799559606,
          "95.0": 10152.034799559606,
          "99.0": 10152.034799559606,
          "99.9": 10152.034799559606,
          "99.99": 10152.034799559606,
          "99.999": 10152.034799559606,
          "99.9999": 10152.034799559606,
          "100.0": 10152.034799559606
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            10147.373078499557,
            10114.938953300541,
            10152.034799559606,
            10123.690436501021,
            10110.35809806559
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7692.568371026669,
        "scoreError": 9.006037337364212,
        "scoreConfidence": [
          7683.562333689305,
          7701.574408364034
        ],
        "scorePercentiles": {
          "0.0": 7689.738375383704,
          "50.0": 7691.888830348401,
          "90.0": 7695.745077937376,
          "95.0": 7695.745077937376,
          "99.0": 7695.745077937376,
          "99.9": 7695.745077937376,
          "99.99": 7695.745077937376,
          "99.999": 7695.745077937376,
          "99.9999": 7695.745077937376,
          "100.0": 7695.745077937376
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7691.457450293571,
            7691.888830348401,
            7689.738375383704,
            7695.745077937376,
            7694.01212117029
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 8411.613177919211,
        "scoreError": 42.9996455098826,
        "scoreConfidence": [
          8368.613532409328,
          8454.612823429094
        ],
        "scorePercentiles": {
          "0.0": 8395.886450419135,
          "50.0": 8414.751233465617,
          "90.0": 8423.801808917962,
          "95.0": 8423.801808917962,
          "99.0": 8423.801808917962,
          "99.9": 8423.801808917962,
          "99.99": 8423.801808917962,
          "99.999": 8423.801808917962,
          "99.9999": 8423.801808917962,
          "100.0": 8423.801808917962
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            8395.886450419135,
            8418.63140834784,
            8414.751233465617,
            8404.994988445505,
            8423.801808917962
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1146.7394465793,
        "scoreError": 40.057978894864256,
        "scoreConfidence": [
          1106.6814676844358,
          1186.7974254741641
        ],
        "scorePercentiles": {
          "0.0": 1132.379396074843,
          "50.0": 1151.6101212418434,
          "90.0": 1157.3983241663855,
          "95.0": 1157.3983241663855,
          "99.0": 1157.3983241663855,
          "99.9": 1157.3983241663855,
          "99.99": 1157.3983241663855,
          "99.999": 1157.3983241663855,
          "99.9999": 1157.3983241663855,
          "100.0": 1157.3983241663855
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1132.379396074843,
            1157.3983241663855,
            1152.8125385278142,
            1139.4968528856145,
            1151.6101212418434
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1146.0415595229542,
        "scoreError": 67.2706689894513,
        "scoreConfidence": [
          1078.770890533503,
          1213.3122285124055
        ],
        "scorePercentiles": {
          "0.0": 1118.2729102423261,
          "50.0": 1146.4478466416526,
          "90.0": 1161.2569824935783,
          "95.0": 1161.2569824935783,
          "99.0": 1161.2569824935783,
          "99.9": 1161.2569824935783,
          "99.99": 1161.2569824935783,
          "99.999": 1161.2569824935783,
          "99.9999": 1161.2569824935783,
          "100.0": 1161.2569824935783
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1161.2569824935783,
            1160.6078074097202,
            1143.622250827494,
            1146.4478466416526,
            1118.2729102423261
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2060.5623202386278,
        "scoreError": 30.38052909215267,
        "scoreConfidence": [
          2030.181791146475,
          2090.9428493307805
        ],
        "scorePercentiles": {
          "0.0": 2051.2317910178112,
          "50.0": 2060.288808906054,
          "90.0": 2071.5561835885596,
          "95.0": 2071.5561835885596,
          "99.0": 2071.5561835885596,
          "99.9": 2071.5561835885596,
          "99.99": 2071.5561835885596,
          "99.999": 2071.5561835885596,
          "99.9999": 2071.5561835885596,
          "100.0": 2071.5561835885596
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2051.2317910178112,
            2055.3937780483147,
            2060.288808906054,
            2064.341039632398,
            2071.5561835885596
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2299.1790890720913,
        "scoreError": 13.078551522789168,
        "scoreConfidence": [
          2286.1005375493023,
          2312.2576405948803
        ],
        "scorePercentiles": {
          "0.0": 2294.5328078804546,
          "50.0": 2299.467997842182,
          "90.0": 2303.533013428662,
          "95.0": 2303.533013428662,
          "99.0": 2303.533013428662,
          "99.9": 2303.533013428662,
          "99.99": 2303.533013428662,
          "99.999": 2303.533013428662,
          "99.9999": 2303.533013428662,
          "100.0": 2303.533013428662
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2299.467997842182,
            2300.841483968547,
            2303.533013428662,
            2294.5328078804546,
            2297.5201422406117
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2463.9562994774933,
        "scoreError": 91.99366746469718,
        "scoreConfidence": [
          2371.9626320127963,
          2555.9499669421903
        ],
        "scorePercentiles": {
          "0.0": 2439.501712259257,
          "50.0": 2465.8595424274868,
          "90.0": 2491.5409561076444,
          "95.0": 2491.5409561076444,
          "99.0": 2491.5409561076444,
          "99.9": 2491.5409561076444,
          "99.99": 2491.5409561076444,
          "99.999": 2491.5409561076444,
          "99.9999": 2491.5409561076444,
          "100.0": 2491.5409561076444
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2439.501712259257,
            2440.1348623852155,
            2482.7444242078627,
            2491.5409561076444,
            2465.8595424274868
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 591.8913924059555,
        "scoreError": 11.552685661783366,
        "scoreConfidence": [
          580.3387067441721,
          603.4440780677388
        ],
        "scorePercentiles": {
          "0.0": 587.3719601674264,
          "50.0": 593.2306966528885,
          "90.0": 594.9785972671784,
          "95.0": 594.9785972671784,
          "99.0": 594.9785972671784,
          "99.9": 594.9785972671784,
          "99.99": 594.9785972671784,
          "99.999": 594.9785972671784,
          "99.9999": 594.9785972671784,
          "100.0": 594.9785972671784
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            590.480022701529,
            593.3956852407551,
            594.9785972671784,
            593.2306966528885,
            587.3719601674264
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1595.7082260062998,
        "scoreError": 52.2294747007503,
        "scoreConfidence": [
          1543.4787513055494,
          1647.9377007070502
        ],
        "scorePercentiles": {
          "0.0": 1575.2892389471224,
          "50.0": 1596.8534687905292,
          "90.0": 1611.2171208794846,
          "95.0": 1611.2171208794846,
          "99.0": 1611.2171208794846,
          "99.9": 1611.2171208794846,
          "99.99": 1611.2171208794846,
          "99.999": 1611.2171208794846,
          "99.9999": 1611.2171208794846,
          "100.0": 1611.2171208794846
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1575.2892389471224,
            1596.8534687905292,
            1591.672444952536,
            1603.5088564618277,
            1611.2171208794846
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1601.6451552048022,
        "scoreError": 40.766391705339856,
        "scoreConfidence": [
          1560.8787634994624,
          1642.411546910142
        ],
        "scorePercentiles": {
          "0.0": 1582.7604130087177,
          "50.0": 1606.4519910322992,
          "90.0": 1607.19801783229,
          "95.0": 1607.19801783229,
          "99.0": 1607.19801783229,
          "99.9": 1607.19801783229,
          "99.99": 1607.19801783229,
          "99.999": 1607.19801783229,
          "99.9999": 1607.19801783229,
          "100.0": 1607.19801783229
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1605.06554047273,
            1607.19801783229,
            1606.4519910322992,
            1582.7604130087177,
            1606.749813677974
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1036.732477467761,
        "scoreError": 11.113510740880086,
        "scoreConfidence": [
          1025.6189667268811,
          1047.845988208641
        ],
        "scorePercentiles": {
          "0.0": 1032.3877084007386,
          "50.0": 1036.7877902750865,
          "90.0": 1040.4793628554557,
          "95.0": 1040.4793628554557,
          "99.0": 1040.4793628554557,
          "99.9": 1040.4793628554557,
          "99.99": 1040.4793628554557,
          "99.999": 1040.4793628554557,
          "99.9999": 1040.4793628554557,
          "100.0": 1040.4793628554557
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1032.3877084007386,
            1036.7877902750865,
            1040.4793628554557,
            1037.3593445039432,
            1036.648181303581
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 420.32389899907014,
        "scoreError": 14.264595624135,
        "scoreConfidence": [
          406.05930337493515,
          434.5884946232051
        ],
        "scorePercentiles": {
          "0.0": 415.694734987057,
          "50.0": 419.94553775198165,
          "90.0": 424.84019678481957,
          "95.0": 424.84019678481957,
          "99.0": 424.84019678481957,
          "99.9": 424.84019678481957,
          "99.99": 424.84019678481957,
          "99.999": 424.84019678481957,
          "99.9999": 424.84019678481957,
          "100.0": 424.84019678481957
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            423.09958020528654,
            424.84019678481957,
            419.94553775198165,
            418.0394452662057,
            415.694734987057
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 560.7030347938464,
        "scoreError": 17.985706650797898,
        "scoreConfidence": [
          542.7173281430486,
          578.6887414446443
        ],
        "scorePercentiles": {
          "0.0": 554.2582234715888,
          "50.0": 559.959059626435,
          "90.0": 566.7320224633743,
          "95.0": 566.7320224633743,
          "99.0": 566.7320224633743,
          "99.9": 566.7320224633743,
          "99.99": 566.7320224633743,
          "99.999": 566.7320224633743,
          "99.9999": 566.7320224633743,
          "100.0": 566.7320224633743
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            563.3023764819388,
            566.7320224633743,
            559.959059626435,
            554.2582234715888,
            559.2634919258954
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 0,
      "jvm": "null/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "Substrate VM",
      "vmVersion": "GraalVM 22.3.0 Java 17 CE",
      "warmupIterations": 0,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 165.601394032237,
        "scoreError": 2.699627726633127,
        "scoreConfidence": [
          162.90176630560387,
          168.30102175887015
        ],
        "scorePercentiles": {
          "0.0": 164.4934519553238,
          "50.0": 165.65721662068034,
          "90.0": 166.27064483780416,
          "95.0": 166.27064483780416,
          "99.0": 166.27064483780416,
          "99.9": 166.27064483780416,
          "99.99": 166.27064483780416,
          "99.999": 166.27064483780416,
          "99.9999": 166.27064483780416,
          "100.0": 166.27064483780416
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            164.4934519553238,
            165.46553902845437,
            166.12011771892253,
            166.27064483780416,
            165.65721662068034
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvmBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 25663.117103938137,
        "scoreError": 2299.0498298556813,
        "scoreConfidence": [
          23364.067274082456,
          27962.16693379382
        ],
        "scorePercentiles": {
          "0.0": 24657.651562839972,
          "50.0": 25856.787369142785,
          "90.0": 26198.259682865635,
          "95.0": 26198.259682865635,
          "99.0": 26198.259682865635,
          "99.9": 26198.259682865635,
          "99.99": 26198.259682865635,
          "99.999": 26198.259682865635,
          "99.9999": 26198.259682865635,
          "100.0": 26198.259682865635
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            24657.651562839972,
            25856.787369142785,
            25638.980967189163,
            25963.905937653126,
            26198.259682865635
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 25469.95316342041,
        "scoreError": 379.82233975104964,
        "scoreConfidence": [
          25090.130823669362,
          25849.77550317146
        ],
        "scorePercentiles": {
          "0.0": 25361.16996270343,
          "50.0": 25490.35865516362,
          "90.0": 25597.470902452704,
          "95.0": 25597.470902452704,
          "99.0": 25597.470902452704,
          "99.9": 25597.470902452704,
          "99.99": 25597.470902452704,
          "99.999": 25597.470902452704,
          "99.9999": 25597.470902452704,
          "100.0": 25597.470902452704
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            25361.16996270343,
            25380.951801707484,
            25490.35865516362,
            25597.470902452704,
            25519.81449507481
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 31368.375557763975,
        "scoreError": 1131.8392989155188,
        "scoreConfidence": [
          30236.536258848457,
          32500.214856679493
        ],
        "scorePercentiles": {
          "0.0": 30877.51326443237,
          "50.0": 31493.382385296707,
          "90.0": 31636.807822515322,
          "95.0": 31636.807822515322,
          "99.0": 31636.807822515322,
          "99.9": 31636.807822515322,
          "99.99": 31636.807822515322,
          "99.999": 31636.807822515322,
          "99.9999": 31636.807822515322,
          "100.0": 31636.807822515322
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            30877.51326443237,
            31493.382385296707,
            31338.929348202815,
            31636.807822515322,
            31495.244968372663
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 24319.115964158438,
        "scoreError": 897.8997949818392,
        "scoreConfidence": [
          23421.216169176598,
          25217.01575914028
        ],
        "scorePercentiles": {
          "0.0": 23947.36669029959,
          "50.0": 24388.724889527468,
          "90.0": 24509.517405342704,
          "95.0": 24509.517405342704,
          "99.0": 24509.517405342704,
          "99.9": 24509.517405342704,
          "99.99": 24509.517405342704,
          "99.999": 24509.517405342704,
          "99.9999": 24509.517405342704,
          "100.0": 24509.517405342704
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            23947.36669029959,
            24248.580428704172,
            24501.390406918268,
            24388.724889527468,
            24509.517405342704
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 16797.265139599716,
        "scoreError": 382.64100262426285,
        "scoreConfidence": [
          16414.624136975453,
          17179.90614222398
        ],
        "scorePercentiles": {
          "0.0": 16651.926908749294,
          "50.0": 16810.672563711054,
          "90.0": 16889.136627644246,
          "95.0": 16889.136627644246,
          "99.0": 16889.136627644246,
          "99.9": 16889.136627644246,
          "99.99": 16889.136627644246,
          "99.999": 16889.136627644246,
          "99.9999": 16889.136627644246,
          "100.0": 16889.136627644246
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            16651.926908749294,
            16750.39038309504,
            16810.672563711054,
            16889.136627644246,
            16884.199214798955
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 23238.867284025717,
        "scoreError": 250.7019613001432,
        "scoreConfidence": [
          22988.165322725574,
          23489.56924532586
        ],
        "scorePercentiles": {
          "0.0": 23165.54313135731,
          "50.0": 23240.066389858803,
          "90.0": 23341.273131295635,
          "95.0": 23341.273131295635,
          "99.0": 23341.273131295635,
          "99.9": 23341.273131295635,
          "99.99": 23341.273131295635,
          "99.999": 23341.273131295635,
          "99.9999": 23341.273131295635,
          "100.0": 23341.273131295635
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            23165.54313135731,
            23205.94857075849,
            23240.066389858803,
            23241.505196858347,
            23341.273131295635
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4783.618833861981,
        "scoreError": 106.06851758677425,
        "scoreConfidence": [
          4677.5503162752075,
          4889.687351448755
        ],
        "scorePercentiles": {
          "0.0": 4735.173249337046,
          "50.0": 4791.44213174095,
          "90.0": 4801.7209063872715,
          "95.0": 4801.7209063872715,
          "99.0": 4801.7209063872715,
          "99.9": 4801.7209063872715,
          "99.99": 4801.7209063872715,
          "99.999": 4801.7209063872715,
          "99.9999": 4801.7209063872715,
          "100.0": 4801.7209063872715
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4735.173249337046,
            4790.1035238192735,
            4799.654358025366,
            4801.7209063872715,
            4791.44213174095
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4852.650911914927,
        "scoreError": 71.88481159457541,
        "scoreConfidence": [
          4780.766100320351,
          4924.5357235095025
        ],
        "scorePercentiles": {
          "0.0": 4821.60459590234,
          "50.0": 4855.604149658029,
          "90.0": 4871.89442046861,
          "95.0": 4871.89442046861,
          "99.0": 4871.89442046861,
          "99.9": 4871.89442046861,
          "99.99": 4871.89442046861,
          "99.999": 4871.89442046861,
          "99.9999": 4871.89442046861,
          "100.0": 4871.89442046861
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4821.60459590234,
            4854.631325023843,
            4859.5200685218115,
            4855.604149658029,
            4871.89442046861
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5998.162154862246,
        "scoreError": 100.95664163504534,
        "scoreConfidence": [
          5897.205513227201,
          6099.118796497291
        ],
        "scorePercentiles": {
          "0.0": 5960.039523936147,
          "50.0": 6012.20300980913,
          "90.0": 6022.935211306928,
          "95.0": 6022.935211306928,
          "99.0": 6022.935211306928,
          "99.9": 6022.935211306928,
          "99.99": 6022.935211306928,
          "99.999": 6022.935211306928,
          "99.9999": 6022.935211306928,
          "100.0": 6022.935211306928
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5960.039523936147,
            5982.24193200688,
            6013.3910972521435,
            6012.20300980913,
            6022.935211306928
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 6797.747423959324,
        "scoreError": 92.3496027712102,
        "scoreConfidence": [
          6705.397821188114,
          6890.097026730534
        ],
        "scorePercentiles": {
          "0.0": 6767.497676423313,
          "50.0": 6806.019591421135,
          "90.0": 6822.308660634158,
          "95.0": 6822.308660634158,
          "99.0": 6822.308660634158,
          "99.9": 6822.308660634158,
          "99.99": 6822.308660634158,
          "99.999": 6822.308660634158,
          "99.9999": 6822.308660634158,
          "100.0": 6822.308660634158
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            6767.497676423313,
            6806.019591421135,
            6815.305658354359,
            6822.308660634158,
            6777.605532963654
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5187.049803111107,
        "scoreError": 30.402331527659722,
        "scoreConfidence": [
          5156.647471583447,
          5217.452134638767
        ],
        "scorePercentiles": {
          "0.0": 5182.40547534042,
          "50.0": 5184.276539107339,
          "90.0": 5201.0556373605295,
          "95.0": 5201.0556373605295,
          "99.0": 5201.0556373605295,
          "99.9": 5201.0556373605295,
          "99.99": 5201.0556373605295,
          "99.999": 5201.0556373605295,
          "99.9999": 5201.0556373605295,
          "100.0": 5201.0556373605295
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5182.70163476916,
            5184.276539107339,
            5182.40547534042,
            5184.809728978091,
            5201.0556373605295
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1053.0263689101644,
        "scoreError": 9.62113350835938,
        "scoreConfidence": [
          1043.405235401805,
          1062.6475024185238
        ],
        "scorePercentiles": {
          "0.0": 1048.6270217959275,
          "50.0": 1053.9429889829762,
          "90.0": 1054.7481078685416,
          "95.0": 1054.7481078685416,
          "99.0": 1054.7481078685416,
          "99.9": 1054.7481078685416,
          "99.99": 1054.7481078685416,
          "99.999": 1054.7481078685416,
          "99.9999": 1054.7481078685416,
          "100.0": 1054.7481078685416
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1048.6270217959275,
            1053.9429889829762,
            1054.7481078685416,
            1053.5447907738712,
            1054.2689351295064
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3689.397713528867,
        "scoreError": 81.05501295199656,
        "scoreConfidence": [
          3608.3427005768704,
          3770.4527264808635
        ],
        "scorePercentiles": {
          "0.0": 3663.0908123075587,
          "50.0": 3684.626260791189,
          "90.0": 3711.469371723584,
          "95.0": 3711.469371723584,
          "99.0": 3711.469371723584,
          "99.9": 3711.469371723584,
          "99.99": 3711.469371723584,
          "99.999": 3711.469371723584,
          "99.9999": 3711.469371723584,
          "100.0": 3711.469371723584
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3663.0908123075587,
            3684.626260791189,
            3711.469371723584,
            3710.177213427179,
            3677.624909394824
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3607.4185438074906,
        "scoreError": 68.41942212242918,
        "scoreConfidence": [
          3538.9991216850613,
          3675.83796592992
        ],
        "scorePercentiles": {
          "0.0": 3580.39277194261,
          "50.0": 3614.0069330005613,
          "90.0": 3627.4891358297514,
          "95.0": 3627.4891358297514,
          "99.0": 3627.4891358297514,
          "99.9": 3627.4891358297514,
          "99.99": 3627.4891358297514,
          "99.999": 3627.4891358297514,
          "99.9999": 3627.4891358297514,
          "100.0": 3627.4891358297514
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3580.39277194261,
            3601.0385659153635,
            3614.0069330005613,
            3614.1653123491697,
            3627.4891358297514
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2411.771242779908,
        "scoreError": 21.259456839518645,
        "scoreConfidence": [
          2390.511785940389,
          2433.0306996194267
        ],
        "scorePercentiles": {
          "0.0": 2402.297693764036,
          "50.0": 2413.0700892824143,
          "90.0": 2416.4875832503208,
          "95.0": 2416.4875832503208,
          "99.0": 2416.4875832503208,
          "99.9": 2416.4875832503208,
          "99.99": 2416.4875832503208,
          "99.999": 2416.4875832503208,
          "99.9999": 2416.4875832503208,
          "100.0": 2416.4875832503208
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2402.297693764036,
            2412.4357119874803,
            2414.56513561529,
            2413.0700892824143,
            2416.4875832503208
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1032.2038742030804,
        "scoreError": 4.8225202701918795,
        "scoreConfidence": [
          1027.3813539328885,
          1037.0263944732724
        ],
        "scorePercentiles": {
          "0.0": 1030.5924866475673,
          "50.0": 1032.4382947186903,
          "90.0": 1033.6197393431523,
          "95.0": 1033.6197393431523,
          "99.0": 1033.6197393431523,
          "99.9": 1033.6197393431523,
          "99.99": 1033.6197393431523,
          "99.999": 1033.6197393431523,
          "99.9999": 1033.6197393431523,
          "100.0": 1033.6197393431523
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1030.5924866475673,
            1033.6197393431523,
            1033.0835918359423,
            1032.4382947186903,
            1031.28525847005
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 809.6347900578123,
        "scoreError": 18.710844283055284,
        "scoreConfidence": [
          790.923945774757,
          828.3456343408676
        ],
        "scorePercentiles": {
          "0.0": 801.292453151841,
          "50.0": 811.5902968715848,
          "90.0": 813.4134540655809,
          "95.0": 813.4134540655809,
          "99.0": 813.4134540655809,
          "99.9": 813.4134540655809,
          "99.99": 813.4134540655809,
          "99.999": 813.4134540655809,
          "99.9999": 813.4134540655809,
          "100.0": 813.4134540655809
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            801.292453151841,
            811.5902968715848,
            812.2325255477725,
            813.4134540655809,
            809.6452206522825
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java",
      "jvmArgs": [],
      "jdkVersion": "17.0.5",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.5+8",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 335.04682054992594,
        "scoreError": 3.263865286829935,
        "scoreConfidence": [
          331.782955263096,
          338.31068583675585
        ],
        "scorePercentiles": {
          "0.0": 333.65011137275576,
          "50.0": 335.15881572302783,
          "90.0": 335.91210564910585,
          "95.0": 335.91210564910585,
          "99.0": 335.91210564910585,
          "99.9": 335.91210564910585,
          "99.99": 335.91210564910585,
          "99.999": 335.91210564910585,
          "99.9999": 335.91210564910585,
          "100.0": 335.91210564910585
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            333.65011137275576,
            335.0644546091842,
            335.15881572302783,
            335.91210564910585,
            335.44861539555615
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "linuxX64Bench": [
    {
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5415.487088142393,
        "scoreError": 93.11015478908145,
        "scoreConfidence": [
          5322.376933353312,
          5508.597242931474
        ],
        "scorePercentiles": {
          "0.00": 5350.582812073181,
          "25.00": 5350.582812073181,
          "50.00": 5387.849269605987,
          "75.00": 5508.0291827480105,
          "90.00": 5508.0291827480105,
          "99.00": 5508.0291827480105,
          "99.90": 5508.0291827480105,
          "99.99": 5508.0291827480105,
          "100.00": 5508.0291827480105
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5508.0291827480105,
            5350.582812073181,
            5387.849269605987
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day1Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5477.548699970517,
        "scoreError": 109.73153373979356,
        "scoreConfidence": [
          5367.817166230724,
          5587.28023371031
        ],
        "scorePercentiles": {
          "0.00": 5395.537748155914,
          "25.00": 5395.537748155914,
          "50.00": 5452.533167559775,
          "75.00": 5584.575184195862,
          "90.00": 5584.575184195862,
          "99.00": 5584.575184195862,
          "99.90": 5584.575184195862,
          "99.99": 5584.575184195862,
          "100.00": 5584.575184195862
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5584.575184195862,
            5395.537748155914,
            5452.533167559775
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 5318.2562379187475,
        "scoreError": 22.484939567364602,
        "scoreConfidence": [
          5295.771298351383,
          5340.741177486112
        ],
        "scorePercentiles": {
          "0.00": 5303.322175752351,
          "25.00": 5303.322175752351,
          "50.00": 5310.638695559734,
          "75.00": 5340.807842444158,
          "90.00": 5340.807842444158,
          "99.00": 5340.807842444158,
          "99.90": 5340.807842444158,
          "99.99": 5340.807842444158,
          "100.00": 5340.807842444158
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            5303.322175752351,
            5340.807842444158,
            5310.638695559734
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day2Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4140.476120933639,
        "scoreError": 28.48893840183366,
        "scoreConfidence": [
          4111.987182531806,
          4168.965059335473
        ],
        "scorePercentiles": {
          "0.00": 4113.988840956563,
          "25.00": 4113.988840956563,
          "50.00": 4143.345189518671,
          "75.00": 4164.094332325684,
          "90.00": 4164.094332325684,
          "99.00": 4164.094332325684,
          "99.90": 4164.094332325684,
          "99.99": 4164.094332325684,
          "100.00": 4164.094332325684
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            4164.094332325684,
            4143.345189518671,
            4113.988840956563
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 13514.339147777071,
        "scoreError": 11.2479342815449,
        "scoreConfidence": [
          13503.091213495527,
          13525.587082058615
        ],
        "scorePercentiles": {
          "0.00": 13504.22433377846,
          "25.00": 13504.22433377846,
          "50.00": 13514.698961575354,
          "75.00": 13524.094147977396,
          "90.00": 13524.094147977396,
          "99.00": 13524.094147977396,
          "99.90": 13524.094147977396,
          "99.99": 13524.094147977396,
          "100.00": 13524.094147977396
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            13514.698961575354,
            13524.094147977396,
            13504.22433377846
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day3Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 12907.791417374146,
        "scoreError": 39.52090727905853,
        "scoreConfidence": [
          12868.270510095088,
          12947.312324653205
        ],
        "scorePercentiles": {
          "0.00": 12881.633491695093,
          "25.00": 12881.633491695093,
          "50.00": 12894.289371987257,
          "75.00": 12947.451388440093,
          "90.00": 12947.451388440093,
          "99.00": 12947.451388440093,
          "99.90": 12947.451388440093,
          "99.99": 12947.451388440093,
          "100.00": 12947.451388440093
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            12947.451388440093,
            12894.289371987257,
            12881.633491695093
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 550.0601825167051,
        "scoreError": 3.3236420838774983,
        "scoreConfidence": [
          546.7365404328276,
          553.3838246005827
        ],
        "scorePercentiles": {
          "0.00": 547.3740154455427,
          "25.00": 547.3740154455427,
          "50.00": 549.6102409205957,
          "75.00": 553.1962911839771,
          "90.00": 553.1962911839771,
          "99.00": 553.1962911839771,
          "99.90": 553.1962911839771,
          "99.99": 553.1962911839771,
          "100.00": 553.1962911839771
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            547.3740154455427,
            553.1962911839771,
            549.6102409205957
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day4Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 540.588739370885,
        "scoreError": 2.514022919121277,
        "scoreConfidence": [
          538.0747164517637,
          543.1027622900064
        ],
        "scorePercentiles": {
          "0.00": 538.0284517537657,
          "25.00": 538.0284517537657,
          "50.00": 541.7296635446527,
          "75.00": 542.0081028142367,
          "90.00": 542.0081028142367,
          "99.00": 542.0081028142367,
          "99.90": 542.0081028142367,
          "99.99": 542.0081028142367,
          "100.00": 542.0081028142367
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            541.7296635446527,
            542.0081028142367,
            538.0284517537657
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 542.0469214474571,
        "scoreError": 0.17229846914776029,
        "scoreConfidence": [
          541.8746229783093,
          542.2192199166049
        ],
        "scorePercentiles": {
          "0.00": 541.8716876783318,
          "25.00": 541.8716876783318,
          "50.00": 542.1221703021049,
          "75.00": 542.1469063619348,
          "90.00": 542.1469063619348,
          "99.00": 542.1469063619348,
          "99.90": 542.1469063619348,
          "99.99": 542.1469063619348,
          "100.00": 542.1469063619348
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            542.1221703021049,
            542.1469063619348,
            541.8716876783318
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day5Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 568.5977594201601,
        "scoreError": 0.5402601832625422,
        "scoreConfidence": [
          568.0574992368976,
          569.1380196034225
        ],
        "scorePercentiles": {
          "0.00": 568.0825262691044,
          "25.00": 568.0825262691044,
          "50.00": 568.6855578318791,
          "75.00": 569.0251941594967,
          "90.00": 569.0251941594967,
          "99.00": 569.0251941594967,
          "99.90": 569.0251941594967,
          "99.99": 569.0251941594967,
          "100.00": 569.0251941594967
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            569.0251941594967,
            568.6855578318791,
            568.0825262691044
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 878.2573985350364,
        "scoreError": 28.81396756654328,
        "scoreConfidence": [
          849.4434309684931,
          907.0713661015797
        ],
        "scorePercentiles": {
          "0.00": 850.0695321714151,
          "25.00": 850.0695321714151,
          "50.00": 885.109668515784,
          "75.00": 899.5929949179098,
          "90.00": 899.5929949179098,
          "99.00": 899.5929949179098,
          "99.90": 899.5929949179098,
          "99.99": 899.5929949179098,
          "100.00": 899.5929949179098
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            899.5929949179098,
            850.0695321714151,
            885.109668515784
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day6Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 294.17444222936575,
        "scoreError": 4.880272481582603,
        "scoreConfidence": [
          289.29416974778314,
          299.05471471094836
        ],
        "scorePercentiles": {
          "0.00": 291.3167355487825,
          "25.00": 291.3167355487825,
          "50.00": 292.0713750714185,
          "75.00": 299.13521606789635,
          "90.00": 299.13521606789635,
          "99.00": 299.13521606789635,
          "99.90": 299.13521606789635,
          "99.99": 299.13521606789635,
          "100.00": 299.13521606789635
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            299.13521606789635,
            292.0713750714185,
            291.3167355487825
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 561.142588115647,
        "scoreError": 7.309869943759731,
        "scoreConfidence": [
          553.8327181718872,
          568.4524580594067
        ],
        "scorePercentiles": {
          "0.00": 556.2306299041755,
          "25.00": 556.2306299041755,
          "50.00": 558.7372319266034,
          "75.00": 568.4599025161621,
          "90.00": 568.4599025161621,
          "99.00": 568.4599025161621,
          "99.90": 568.4599025161621,
          "99.99": 568.4599025161621,
          "100.00": 568.4599025161621
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            568.4599025161621,
            556.2306299041755,
            558.7372319266034
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day7Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 565.6988058825314,
        "scoreError": 5.0013119866702995,
        "scoreConfidence": [
          560.697493895861,
          570.7001178692017
        ],
        "scorePercentiles": {
          "0.00": 560.7417094292575,
          "25.00": 560.7417094292575,
          "50.00": 567.126755039892,
          "75.00": 569.2279531784446,
          "90.00": 569.2279531784446,
          "99.00": 569.2279531784446,
          "99.90": 569.2279531784446,
          "99.99": 569.2279531784446,
          "100.00": 569.2279531784446
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            569.2279531784446,
            560.7417094292575,
            567.126755039892
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 1293.0196485931338,
        "scoreError": 1.3584552289019924,
        "scoreConfidence": [
          1291.6611933642318,
          1294.3781038220357
        ],
        "scorePercentiles": {
          "0.00": 1291.714177237146,
          "25.00": 1291.714177237146,
          "50.00": 1293.2687419002102,
          "75.00": 1294.0760266420446,
          "90.00": 1294.0760266420446,
          "99.00": 1294.0760266420446,
          "99.90": 1294.0760266420446,
          "99.99": 1294.0760266420446,
          "100.00": 1294.0760266420446
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            1291.714177237146,
            1293.2687419002102,
            1294.0760266420446
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day8Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 333.4551875562366,
        "scoreError": 1.6182282030896185,
        "scoreConfidence": [
          331.83695935314694,
          335.0734157593262
        ],
        "scorePercentiles": {
          "0.00": 332.2164023485971,
          "25.00": 332.2164023485971,
          "50.00": 333.12904516628447,
          "75.00": 335.02011515382816,
          "90.00": 335.02011515382816,
          "99.00": 335.02011515382816,
          "99.90": 335.02011515382816,
          "99.99": 335.02011515382816,
          "100.00": 335.02011515382816
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            335.02011515382816,
            333.12904516628447,
            332.2164023485971
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 286.63634352468983,
        "scoreError": 2.113309602844017,
        "scoreConfidence": [
          284.5230339218458,
          288.74965312753386
        ],
        "scorePercentiles": {
          "0.00": 284.57250298572563,
          "25.00": 284.57250298572563,
          "50.00": 287.12688453172484,
          "75.00": 288.2096430566189,
          "90.00": 288.2096430566189,
          "99.00": 288.2096430566189,
          "99.90": 288.2096430566189,
          "99.99": 288.2096430566189,
          "100.00": 288.2096430566189
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            288.2096430566189,
            284.57250298572563,
            287.12688453172484
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2022.Day9Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 75.57182016682339,
        "scoreError": 0.1607527669859325,
        "scoreConfidence": [
          75.41106739983745,
          75.73257293380932
        ],
        "scorePercentiles": {
          "0.00": 75.4138630603642,
          "25.00": 75.4138630603642,
          "50.00": 75.61249218784333,
          "75.00": 75.68910525226259,
          "90.00": 75.68910525226259,
          "99.00": 75.68910525226259,
          "99.90": 75.68910525226259,
          "99.99": 75.68910525226259,
          "100.00": 75.68910525226259
        },
        "scoreUnit": "ops/sec",
        "rawData": [
          [
            75.61249218784333,
            75.68910525226259,
            75.4138630603642
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
