name: Get inputs

on:
  workflow_call:
    inputs:
      year:
        required: false
        type: number
    secrets:
      SESSION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Day
        id: get-day
        run: |
          from datetime import datetime, timedelta, timezone
          import os
          tz = timezone(timedelta(hours=-5))
          year = ${{ inputs.year }} or 2022
          day = max(0, min(25, (datetime.now(tz) - datetime(year, 12, 1, 0, 0, 0, 0, tz)).days + 1))
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            print("year=" + str(year), file=f)
            print("day=" + str(min(25, max(0, day))), file=f)
            print("days=" + ' '.join(map(str, range(1, day + 1))), file=f)
        shell: python
      - id: cache
        uses: actions/cache@v3
        with:
          key: inputs-${{ steps.get-day.outputs.day }}
          restore-keys: inputs-
          path: day*.txt
      - name: Download inputs
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          for day in ${{ steps.get-day.outputs.days }}; do
            [[ -e day$day.txt ]] || curl -A https://github.com/ephemient/aoc2022/blob/main/.github/workflows/get-inputs.yml -b session=$SESSION -o day$day.txt -f https://adventofcode.com/${{ steps.get-day.outputs.year }}/day/$day/input
          done
        shell: bash --noprofile --norc -euxo pipefail {0}
        env:
          SESSION: ${{ secrets.SESSION }}
      - uses: actions/upload-artifact@v3
        with:
          name: inputs
          path: day*.txt
