name: Kotlin CI

on:
  push:
    branches: [ main ]
    paths: [ kt/** ]
  pull_request:
    branches: [ main ]
    paths: [ kt/** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: actions/cache@v3
        with:
          key: kt-${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-build
          restore-keys: |
            kt-${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-
            kt-${{ runner.os }}-konan-
          path: ~/.konan
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :check :assembleBenchmarks
          build-root-directory: kt

  graalvm-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          components: native-image
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :graalvm:nativeCompile :graalvm:nativeTest
          build-root-directory: kt

  gradle-wrapper-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
