name: Python CI

on:
  push:
    branches: [ main ]
    paths: [ py/** ]
  pull_request:
    branches: [ main ]
    paths: [ py/** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - uses: abatilo/actions-poetry@v2
      - run: poetry install --no-interaction --no-root
        working-directory: py
      - run: poetry run pylint aoc2022
        working-directory: py
      - run: poetry run black . --check
        working-directory: py
      - run: poetry run isort . --check
        working-directory: py
      - run: poetry run pytest
        working-directory: py
